Bugfix/37982 widget names in charts
wirenboard/homeui pull request #215
Opened 2021-08-03 14:32 UTC by KraPete

Сделано на базе https://github.com/wirenboard/homeui/pull/214 так что надо смотреть только второй коммит.

Проблема в том, что при загрузке графика, если были выбраны контролы из виджетов, их названия подменяются на названия контролов.
Список контролов для отображения у нас передаётся в url.  Идёт список устройств через точку запятую, потом слэш и список каналов снова через точку запятую.
Для виджетов в список устройств пишу название виджета, в список каналов пустую строку.

2021-08-05 15:03 UTC, webconn approved these changes

2021-08-05 15:04 UTC, webconn commented
Сначала посмотрел второй коммит, потом закомментил, а потом уже и остальные глянул %)

2021-08-06 10:56 UTC, evgeny-boger requested changes
насколько я понимаю, если будет больше 2048 символов в сумме, то браузер это порежет.
Может писать не имена виджетов, а их id?

2021-08-06 12:17 UTC, KraPete commented
1. Мне вообще не очень нравится, что оно в URL прямым текстом пакуется. Вот явно же никто руками это не набирает. Может прикрутить упаковку для всего этого и в URL как токен добавлять? Например gzip или вообще protobuf.
Вообще зачем эта фича сделана? Делиться графиками?
2. Сейчас id может поменяться при добавлении и удалении виджетов. Там просто номер по порядку. По хорошему надо uid делать. Тогда это лучше чем название и компактнее.

2021-08-06 12:19 UTC, KraPete commented
Вот как тут https://json-editor.github.io/json-editor, по кнопке direct link.

2021-08-06 12:20 UTC, KraPete commented
```javascript  
var updateDirectLink = function () {
    var url = window.location.href.replace(/\?.*/, '')
    url += '?data='
    url += LZString.compressToBase64(JSON.stringify(data))
    directLink.href = url
  }
```

2021-08-06 13:07 UTC, webconn commented
Плюсую за uid, но это про не очень близкое будущее. И думаю, что есть смысл потом это сделать как альтернативный парсер, наряду с обычным плейнтекстовым именем. А обычное имя виджета удобно использовать откуда угодно, генерить ссылки без лишних библиотек и секретных знаний, так что я бы эту возможность как минимум не убирал бы.

> насколько я понимаю, если будет больше 2048 символов в сумме, то браузер это порежет.
> Может писать не имена виджетов, а их id?

А насколько быстро мы можем достигнуть этих 2048 символов в реальности? На 3-4 графика этого как будто в любом случае должно хватить, а если будут запросы на больше, то можно допилить и альтернативный формат ссылки

2021-08-11 07:25 UTC, evgeny-boger commented
>А насколько быстро мы можем достигнуть этих 2048 символов в реальности? 
у меня получалось даже без виджетов

>var updateDirectLink

выглядит очень просто, давай внедрим

>Сейчас id может поменяться при добавлении и удалении виджетов. Там просто номер по порядку. По хорошему надо uid делать. Тогда это лучше чем название и компактнее.

так зачем uid? У нас не было там цели сделать стабильные ссылки, которыми как-то можно делиться. По такой же логике и сам виджет можно переименовать и ссылка попортится.

Сейчас нам просто нужно, чтобы F5 в браузере работал и открытие во вкладке работало и всё, только для этого нужно кодирование параметров в  URL.

2021-08-12 15:49 UTC, evgeny-boger approved these changes

2021-08-13 07:32 UTC, KraPete commented
Rebase https://github.com/wirenboard/homeui/pull/218

2021-08-13 07:32 UTC, closed without merging