Multiple axes are added to charts on History page
wirenboard/homeui pull request #219
Opened 2021-08-13 14:54 UTC by KraPete

2021-08-17 10:42 UTC, webconn requested changes

2021-08-17 10:42 UTC, webconn commented on app/scripts/controllers/historyController.js
> +        if (stringChartsCount == 1 && boolChartsCount == 0 && commonCharsCount == 0) {       // Один строковый
Давай попробуем объединить эти два длинных ифа: сделаем один, в котором проинициализируем переменную строкой, а потом будем перебирать её значение свитчкейсами. А то тут довольно замысловатые условия, уже вижу, как они однажды ломаются. Тогда и комменты по сути не понадобятся.

2021-08-17 10:42 UTC, webconn commented on app/scripts/controllers/historyController.js
> +        this.hasErrors = false;
Вижу, что в plotly это называется errors, но однажды, если мы решим отображать на графике наши ошибки из meta/error, это может вызвать путаницу. Не призыв к действию, но повод подумать

2021-08-17 10:42 UTC, webconn commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
а для чего у первой и второй осей расхождение снизу?

2021-08-17 10:42 UTC, webconn commented on app/scripts/controllers/historyController.js
> +        var chart = {
Раньше же было лучше? А сейчас chart переопределился

2021-08-17 12:27 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
plolty почему-то рисует 0X для разных осей в разных местах. Потому я и поднял её повыше, чтоб не было двух линий в паре пикселей друг от друга.

2021-08-17 12:36 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
![изображение](https://user-images.githubusercontent.com/86825564/129726640-31a09001-77b7-49b1-945d-53d04a62eb87.png)

2021-08-17 12:37 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
Оранжевый 0 ниже синего

2021-08-17 12:39 UTC, webconn commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
Это картинка после смещения на -0.2? А как исходное выглядит?

2021-08-17 12:48 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
Это 0 по умолчанию.

2021-08-17 12:49 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
![изображение](https://user-images.githubusercontent.com/86825564/129728386-d0b322eb-3017-4bba-9aae-d9f10b1c658e.png)
Вот со смещением

2021-08-17 12:51 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
Без смещения
![изображение](https://user-images.githubusercontent.com/86825564/129728667-8f32311e-a119-4dea-9280-bc6748af7b58.png)

Со смещением
![изображение](https://user-images.githubusercontent.com/86825564/129728798-9251ee77-b75e-436a-91b6-9cc7514caca5.png)

2021-08-17 13:09 UTC, webconn commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
Что-то какие-то костыли. Тема со смещением тоже некрасиво выглядит: получается два нуля, которые на деле не сразу-то и понятно, к какому из графиков относятся

2021-08-17 14:08 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
Приму предложения :)

2021-08-17 15:53 UTC, webconn commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
https://community.plotly.com/t/is-it-possible-to-have-multiple-y-axis-0-zero-positions-in-same-line/23236

2021-08-18 04:49 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
Ну клёво. Посчитаем всё руками. Тогда уже и рсавть сими можно :)

2021-08-18 08:01 UTC, webconn commented on app/scripts/controllers/historyController.js
> +            axis.range = [-0.2, 1.2];
Ну вот на синтетических примерах у меня не получилось воспроизвести, но я и не сильно старался. Но дичь же, если это нельзя решить как-то иначе

2021-08-19 12:15 UTC, webconn approved these changes
Добавь чуть больше информации в комментах, чтобы это место при рефакторинге удобней было пересмотреть, и вливаем

2021-08-19 12:15 UTC, webconn commented on app/scripts/controllers/historyController.js
> +    fixAxes(minValue, maxValue) {
Здесь бы на месте побольше информации о том, что именно мы чиним и почему. Может, даже со ссылкой на форум plotly. Этот код тут не от хорошей жизни, так что думаю, что будущим поколениям лучше знать об этом: вдруг эту тему когда-то починят )

2021-08-20 07:36 UTC, KraPete commented
Rebase https://github.com/wirenboard/homeui/pull/220

2021-08-20 07:36 UTC, closed without merging