Feature/wb diag collect
wirenboard/homeui pull request #250
Opened 2021-09-14 11:07 UTC by sevenzik

Задача № 38500

2021-09-16 09:27 UTC, webconn commented on app/scripts/controllers/diagnosticController.js
> +class DiagnosticCtrl {
Тут никак не проверяется, что сам сервис доступен на контроллере. Есть смысл посмотреть, как это сделано в обновлялке прошивок и сделать хотя бы аналогично

2021-09-16 09:27 UTC, webconn commented on app/scripts/controllers/diagnosticController.js
> +        // TODO: серийник контроллера в имя файла
это ещё актуально?

2021-09-16 09:27 UTC, webconn commented on app/scripts/controllers/diagnosticController.js
> +          $scope.downloadDataBtn.innerHTML = "Collecting...";
Здесь бы ещё таймаут отрабатывать, и выводить ошибку, если ответ не пришёл

2021-09-16 09:27 UTC, webconn commented on app/scripts/controllers/diagnosticController.js
> +          $scope.downloadDataBtn.innerHTML = "Download";
Всё же хочу здесь проверку того, что до файла можно достучаться. И если нельзя, то в интерфейс вывести путь, откуда этот файл можно забрать из файловой системы контроллера

2021-09-16 10:13 UTC, sevenzik commented on app/scripts/controllers/diagnosticController.js
> +        // TODO: серийник контроллера в имя файла
нет
вытаскиваю со стороны сервиса, а не веба

2021-09-17 08:53 UTC, webconn commented
@KraPete глянь тоже, пожалуйста

2021-09-17 09:30 UTC, KraPete requested changes

2021-09-17 09:30 UTC, KraPete commented on app/scripts/controllers/diagnosticController.js
> +      mqttClient.addStickySubscription("/rpc/v1/diag/main/diag/" + mqttClient.getID() + "/+", function(msg) {
У нас же есть стандартная обёртка над RPC с ошибками и таймаутами. Стоит её использовать.

2021-09-17 09:30 UTC, KraPete commented on app/views/system.html
> +        <h3 class="panel-title"><i class="glyphicon glyphicon-download"></i> Collect diagnostic data</h3>
Надо перевести на русский. И остальные строки тоже

2021-09-17 09:30 UTC, KraPete commented on app/views/system.html
> +        <button id="downloadDiag" type="button" disabled class="btn btn-success btn-lg"
Здесь не надо `show="ready"` ?

2021-09-17 09:30 UTC, KraPete commented on app/scripts/controllers/diagnosticController.js
> +    $scope.downloadDataBtn = $element[0].querySelector('#downloadDiag');
https://docs.angularjs.org/guide/controller#
Не рекомендуется манипулировать DOM из контроллера. Стоит всё вынести в view

2021-09-17 10:52 UTC, KraPete commented on app/scripts/controllers/diagnosticController.js
> +        var xmlHttp = new XMLHttpRequest();
Может, использовать `fetch`, он более модерновый?

2021-09-27 06:12 UTC, KraPete requested changes
У меня ещё оставлись вопросы по логике работы:
1. Как пользователю запросить файл повторно?
2. Для проверки доступности файла, он выкачивается весь. Может, как-то только заголовок выкачать или что-то более экономное по трафику и времени?
3. У RPC таймаут 60 секунд. Этого хватит для формирования файла?

2021-09-27 06:12 UTC, KraPete commented on app/scripts/controllers/diagnosticController.js
> +        var filename = $scope.path.substring(14)
Опять магические 14. Если оставлять, надо в константу выносить

2021-09-27 12:02 UTC, sevenzik commented on app/scripts/controllers/diagnosticController.js
> +  constructor($scope, $timeout, $element, DiagnosticProxy, MqttRpc, whenMqttReady) {
3) да 
1) на данный момент никак, кроме обновления страницы
2) подумаю

2021-09-27 16:39 UTC, sevenzik commented on app/scripts/controllers/diagnosticController.js
> +              var filename = path.substring(14);
Формат: полный путь,  _/var/www/diag/<filename>_ .
14 - собственно, длина строки _/var/www/diag/_  .
Можно захардкодить либо 14, либо _/var/www/diag/_  и тогда отдавать утилитой только имя файла (путь нужен, чтобы сказать пользователю, если файл недоступен, где он лежит).
Либо возвращать утилитой и имя файла, и полное имя файла от корня и не заниматься этой логикой здесь. (Звучит как лучший план, т.к. тогда в будущем изменения в утилите не обязательно будут требовать изменения в homeui).

2021-09-27 16:40 UTC, sevenzik commented on app/views/system.html
> +            Время ожидания вышло
На данный момент ничего, кроме обновления страницы

2021-09-28 10:08 UTC, KraPete requested changes
Моя последняя придирка - у тебя отступы и пробелы не единообразно сделаны. Где-то 2 пробела, где-то - 4, где-то после `(` или перед `=>` есть пробел, где-то - нет.

2021-09-28 10:09 UTC, KraPete commented
Ну и changelog надо обновить

2021-09-28 12:33 UTC, sevenzik commented
Что произошло в **_changelog_**, я не понял (массовое стирание пробелов в конце строк, которое я не делал).

2021-09-29 11:17 UTC, KraPete commented
Чё-то не собралось

2021-09-29 14:54 UTC, sevenzik commented
Я поменял ровным счётом ничего, теперь собралось

2021-09-30 07:20 UTC, KraPete approved these changes

2021-09-30 07:34 UTC, webconn commented
На всякий случай напоминаю, что у нас есть [правила](https://github.com/wirenboard/codestyle/blob/master/workflow.md), как мержить такие ветки. Надо будет сделать ветку с суффксом `-rebase`, отребейзить на мастер, слить коммиты и отдельным PR влить

2021-09-30 11:05 UTC, closed without merging

2021-09-30 11:30 UTC, sevenzik commented
https://github.com/wirenboard/homeui/pull/264 - rebase ветки для вливания