wb-mqtt-serial metrics page
wirenboard/homeui pull request #251
Opened 2021-09-16 06:42 UTC by KraPete

2021-09-20 16:35 UTC, webconn requested changes

2021-09-20 16:35 UTC, webconn commented on app/index.ejs
> +                            <a data-toggle="collapse" data-target=".navbar-ex1-collapse" ui-sref="serial-metrics">{{'navigation.menu.serial-metrics' | translate}}</a>
У меня этот пункт меню ни на русском, ни на английском не перевёлся, а до сброса кеша вообще ссылки не было, пришлось `ctrl-shift-r` делать для отображения

2021-09-20 16:35 UTC, webconn commented on app/scripts/i18n/serial-metrics/ru.json
> +            "interval": "Интервал опроса",
Думаю, тут стоит уточнить, за какой период считается эта статистика

2021-09-20 16:35 UTC, webconn commented on app/views/serial-metrics.html
> +
Тут никак не проверяется, что serial умеет отдавать метрики, хорошо бы сделать примерно как со страничкой обновления прошивки

2021-09-20 16:48 UTC, KraPete commented on app/views/serial-metrics.html
> +
Да! Но:
1. Страничка обновления прошивки ужасный пример. Там явно делается подписка на топик с прогрессом обновления прошики, и по нему определяется наличие сервиса. Тут ничего подобного нет.
2. У нас в RPC публикуются `1` в топиках с методами. К сожалению, в homeui это никак не обрабатывается.
3. MQTT - асинхронный. Если подписаться на топики RPC, сколько ждать получения сообщения? Что делать в момент ожидания. Крутить спиннер или как в некоторых местах у нас говорить, что ничего нет, а потом неожиданно грузить новый интефейс через несколько секунд, пока пользователь пытается понять чтоже за фигня?

2021-09-20 16:52 UTC, KraPete commented on app/views/serial-metrics.html
> +
Потому я и остановился на варианте с кнопкой, доступной всегда. Жмёшь - крутится спиннер, ждём таймаут для RPC, если нет ответа, получаем ошибку с текстом.

2021-09-20 16:57 UTC, KraPete commented on app/scripts/i18n/serial-metrics/ru.json
> +            "interval": "Интервал опроса",
Можешь больше описать, что хочешь увидеть? Не совсем понял

2021-09-20 17:04 UTC, webconn commented on app/views/serial-metrics.html
> +
А ещё сделать так, чтобы при входе на страницу, если RPC доступен, сразу загрузить статистику, а кнопку переименовать в Reload и поместить справа

2021-09-20 17:10 UTC, webconn commented on app/views/serial-metrics.html
> +
> Да! Но:
> 
>     1. Страничка обновления прошивки - ужасный пример. Там явно делается подписка на топик с прогрессом обновления прошивки, и по нему определяется наличие сервиса. Тут ничего подобного нет.
Ну там это хоть как-то делается, в пункте 2 ты отлично описываешь, как это должно работать.
>     2. У нас в RPC публикуются `1` в топиках с методами. К сожалению, в homeui это никак не обрабатывается.

>     3. MQTT - асинхронный. Если подписаться на топики RPC, сколько ждать получения сообщения? Что делать в момент ожидания. Крутить спиннер или, как в некоторых местах у нас, говорить, что ничего нет, а потом неожиданно грузить новый интерфейс через несколько секунд, пока пользователь пытается понять что же за фигня?

Думаю, сейчас нормально будет секунд 5 крутить спиннер. Если ничего не дождёмся, вывести плашку, что сервис недоступен (можно даже предложить обновиться до нужной версии serial). Если дождёмся - сразу загрузить статистику, и добавить кнопку reload справа для обновления (и рядом с ней написать серым шрифтом время, в которое был последний раз загружен ответ).

Как пользователь, я скорее думаю, что за фигня, когда вижу интерфейс того, чего нет, а потом оно просто говорит мне `topic timeout, я не знаю, что у меня на контроллере есть`

2021-09-20 17:11 UTC, webconn commented on app/scripts/i18n/serial-metrics/ru.json
> +            "interval": "Интервал опроса",
Конкретно про колонки "Интервал опроса", оно же в serial собирает статистику за минуту (или за всё время работы сервиса?)

2021-09-29 17:03 UTC, webconn reviewed
![Screenshot_20210929_200037](https://user-images.githubusercontent.com/1550335/135315525-132c97f8-51b5-434b-bf0b-8b382cc20f10.png)
Не знаю, сюда ли об этом, но тут появилась эта строка (общая на устройство), и было бы круто в неё вписать суммарные метрики (там, где возможно). Или вообще их не выводить. И точно стоит выделить эту строку цветом, кажется, будет удобно для разделения таблицы по устройствам

2021-09-30 06:32 UTC, KraPete commented on app/scripts/controllers/serialMetricsController.js
> +            });
> ![Screenshot_20210929_200037](https://user-images.githubusercontent.com/1550335/135315525-132c97f8-51b5-434b-bf0b-8b382cc20f10.png) Не знаю, сюда ли об этом, но тут появилась эта строка (общая на устройство), и было бы круто в неё вписать суммарные метрики (там, где возможно). Или вообще их не выводить. И точно стоит выделить эту строку цветом, кажется, будет удобно для разделения таблицы по устройствам

Это строка не про то. Это предварительные и завершающие запросы при опросе устройства. Открытие и закрытие сессии, авторизация и т.п. Т.е. время на шине, которое занимает устройство, но не для запроса данных.

2021-09-30 08:45 UTC, webconn commented on app/scripts/controllers/serialMetricsController.js
> +            });
Если честно, это как-то контринтуитивно. Может, переделаем, чтобы эти дополнительные запросы отдельным пунктом выводились, а под общим пунктом про устройство общую статистику по нему?

2021-09-30 10:41 UTC, KraPete commented on app/scripts/controllers/serialMetricsController.js
> +            });
Сделал для запросов управления сессией отдельные метрики [тут](https://github.com/wirenboard/wb-mqtt-serial/pull/298).

2021-09-30 12:01 UTC, webconn approved these changes

2021-09-30 12:26 UTC, KraPete commented
Rebase https://github.com/wirenboard/homeui/pull/265

2021-09-30 12:26 UTC, closed without merging