Support for translations in JSON Schema templated parameters is added
wirenboard/homeui pull request #261
Opened 2021-09-28 13:18 UTC by KraPete

Добавил в шаблонизатор для json-editor поддержку переводов значений. Надо для перевода hwconf, т.к. там надписи берутся из значений JSON (т.е. самого конфига).

2021-10-05 08:21 UTC, evgeny-boger requested changes
хочу видеть PR в json-edtitor

2021-10-05 08:38 UTC, KraPete commented
Вот жеж https://github.com/wirenboard/json-editor/pull/1

2021-10-05 11:45 UTC, evgeny-boger approved these changes

2021-10-06 04:31 UTC, KraPete commented
Rebase https://github.com/wirenboard/homeui/pull/267

2021-10-06 04:31 UTC, closed without merging