Feature/44076 collapsible devices list
wirenboard/homeui pull request #300
Opened 2022-01-17 05:00 UTC by KraPete

Основано на это https://github.com/wirenboard/homeui/pull/299

2022-01-17 09:24 UTC, webconn requested changes

2022-01-17 09:24 UTC, webconn commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +                this.container.style.paddingBottom = '9px'
Тоже магия отображения в логике. Можно это с темой связать?

Кстати, связанный вопрос: а у наших редакторов появляются свои классы (для CSS)?

2022-01-17 09:24 UTC, webconn commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +                validVal.i = i
А это нормально с учётом, что `validVal` обозначен выше как `const`?

2022-01-17 09:24 UTC, webconn commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +                if (!this.collapsed || !this.schema.options || this.schema.options.disable_collapse) {
Если не будет задано `this.schema.options`, это условие будет `true` (т.е. как будто `disable_collapse == true` по умолчанию). Это корректно, или надо объединить скобками последние два предиката?

2022-01-17 09:24 UTC, webconn commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +            this.container.style = ''
`style.display`?

2022-01-17 09:24 UTC, webconn commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +            this.editors[this.type].editor_holder.style = ''
`style.display`? Или мы тут и выше специально все стили сбрасываем?

2022-01-17 09:30 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-array-editor.js
> +            if (JSONEditor.defaults.language === 'ru') {
Приму любые предложения как это организовать.
1. В схему это нельзя запихнуть, т.к. к схеме не относится.
2. Надо размещать в массиве со строками самого json-editor. Тоже странно, редактор вроде внешний, а строки его в коде json-editor'а.

Ну и всё, больше нет общих мест с переводами.

2022-01-17 09:31 UTC, webconn commented on app/scripts/components/json-editor/collapsible-array-editor.js
> +            if (JSONEditor.defaults.language === 'ru') {
А с переводами самого homeui можно положить?

2022-01-17 09:32 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +                validVal.i = i
Я это из кода оригинального редактора массива утащил.

2022-01-17 09:37 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +            this.container.style = ''
Это я тоже утащил из оригинального редактора, возможно, они что-то хотели этим сказать

2022-01-17 09:39 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +            this.editors[this.type].editor_holder.style = ''
И это тоже из оригинального редактора. Не знаю, зачем они стили обнуляют.

2022-01-17 09:58 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-array-editor.js
> +            if (JSONEditor.defaults.language === 'ru') {
Сделал в функции добаление английской строки, русскую положил в перевод json-editor'а

2022-01-17 11:07 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +                if (!this.collapsed || !this.schema.options || this.schema.options.disable_collapse) {
Вообще убрал, это тут не нужно

2022-01-17 11:08 UTC, KraPete commented on debian/changelog
> +  * "Collapse all items" button is added to devices list in wb-mqtt-serial.conf
Переписал

2022-01-17 11:12 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +            this.container.style = ''
А нет. Это я с paddingBottom игрался. Если развёрнуто, добавлял = 0, т.к. вложенные редакторы имеют свой padding-bottom. Т.е. если в 0 не поставить, то будет широкая полоса внизу. Если свёрнуто, то padding нужен, т.к. видимые элементы не имеют его, и граница панели прилипает к кнопкам.

2022-01-17 11:15 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +            this.editors[this.type].editor_holder.style = ''
Сделал `style.dusplay = ''`, т.к. действительно при сворачивании мы его только трогаем

2022-01-17 11:19 UTC, KraPete commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +            this.container.style = ''
`display` то зачем? Сделал только `paddingBottom`.

2022-01-19 08:48 UTC, webconn approved these changes

2022-01-19 12:35 UTC, KraPete commented
Rebase https://github.com/wirenboard/homeui/pull/301

2022-01-19 12:35 UTC, closed without merging