Support for units in /meta JSON
wirenboard/homeui pull request #304
Opened 2022-01-25 14:52 UTC by KraPete

Добавил в JSON  в `/meta` контрола параметры `units` и `units_power`.
Результирующая единица измерения будет `units`*10^`units_power`. Для базовых степеней сделал добавление префикса при отображении в интерфейсе.
В топик `/meta/units` для совместимости публикуется название уже с префиксом.
Если публиковать в `/meta/units`, как описано в задаче, единицы имерения без множителя, то придётся менять публикуемые значения, это сломает совместимость со сторонним софтом. Ещё можно получить переполнение, есть будут гига или пико величины.

2022-01-27 10:10 UTC, webconn commented on app/scripts/i18n/units/en.json
> +            "-6": "u",
Ну раз уж тройку в кубометрах нарисовал красиво, можно было бы сюда μ написать :)

2022-01-27 10:10 UTC, webconn commented on app/scripts/i18n/units/ru.json
> +            "-2": "санти",
А почему тут не буквами, как в английской? `с, м, мк, н, п`

2022-01-27 10:10 UTC, webconn commented on app/scripts/i18n/units/ru.json
> +        "kWh": "кВтч",
А где-то ниже это записано как `"kw*h"`

2022-02-02 21:04 UTC, evgeny-boger requested changes
1) хотелось бы сразу видеть изменения в conventions.md. Кстати, там сейчас вообще, кажется, нет ничего про JSON
2) можешь прислать примеров, как что будет выглядеть в MQTT?  Я так и не понял.

2022-02-02 21:06 UTC, evgeny-boger commented
ещё меня немного беспокоит пересечение с meta/precision. Тоже хочется посмотреть на примеры, как это обрабатывается.

2022-02-10 05:52 UTC, KraPete commented
@evgeny-boger  Как я уже писал выше, cтепень не влияет на преобразование числа, иначе мы сломаем обратную совместимость. По этому же `/meta/precision` не пересекается ни с чем, т.к. влияет только на конкретное число.
Например, было:
```
/devices/test/controls/Heat power                 11.11
/devices/test/controls/Heat power/meta/type       heat_power
/devices/test/controls/Heat power/meta/precision  0.01
``` 

heat_power у нас в ГКал

стало:
```
/devices/test/controls/Heat power                    11.11
/devices/test/controls/Heat power/meta/type          heat_power
/devices/test/controls/Heat power/meta/precision     0.01
/devices/test/controls/Heat power/meta               {"units": "cal", "units_power": 9, "type": "heat_power", "precision": 0.01}
/devices/test/controls/Heat power/meta/units         Gcal
```

`Gcal` в `/meta/units` формирует libwbmqtt1 из степени и базовой единицы измерения. Надо, если wb-mqtt-homeui старый. Но в принципе можно и не публиковать.

2022-02-11 06:09 UTC, evgeny-boger commented
так а кто-то имеет право публиковать heat_power, но с heat_power не 9, а 6 например?
какие у нас будут требования по обратной совместимости?

2022-02-11 06:15 UTC, KraPete commented
> так а кто-то имеет право публиковать heat_power, но с heat_power не 9, а 6 например? какие у нас будут требования по обратной совместимости?

homeui в первую очередь смотрит на "units" и "units_power" в JSON. Если их нет, то уже в тип контрола. Я вообще могу не публиковать `type` из serial, но тогда надо будет иметь новый homeui.

2022-02-11 06:34 UTC, evgeny-boger commented
так ты не ответил на мой вопрос. Надо всё-таки сформулировать что с чем будет совместимо.

2022-02-11 06:46 UTC, KraPete commented
> так ты не ответил на мой вопрос. Надо всё-таки сформулировать что с чем будет совместимо.

Тогда я не понимаю вопрос. Старые драйверы, которые не умеют в units в JSON. Будут публиковать только type. type разбирается в homeui как раньше. Если драйвер новый, то он опубликует units и homeui будет смотреть в них, а не в type.

2022-02-11 06:51 UTC, evgeny-boger commented
тогда если новый драйвер опубликует
```
/devices/test/controls/Heat power                    111.1
/devices/test/controls/Heat power/meta/type          heat_power
/devices/test/controls/Heat power/meta/precision     0.01
/devices/test/controls/Heat power/meta               {"units": "cal", "units_power": 8, "type": "heat_power", "precision": 0.1}
```

то старый homeui покажет 111.1 GCal, а новый - 11.11 GCal, хотя драйвер имел в виду 11.11 GCal.

Мы такое разрешим делать?

2022-02-11 07:08 UTC, KraPete commented
> тогда если новый драйвер опубликует
> 
> ```
> /devices/test/controls/Heat power                    111.1
> /devices/test/controls/Heat power/meta/type          heat_power
> /devices/test/controls/Heat power/meta/precision     0.01
> /devices/test/controls/Heat power/meta               {"units": "cal", "units_power": 8, "type": "heat_power", "precision": 0.1}
> ```
> 
> то старый homeui покажет 111.1 GCal, а новый - 11.11 GCal, хотя драйвер имел в виду 11.11 GCal.
> 
> Мы такое разрешим делать?

Сейчас я ещё публикую `/meta/units`, в первом примере я это показал. В твоём примере там будет `cal*10^8` и текущий homeui отобразит не `Gcal`, а именно это.

2022-02-11 08:55 UTC, evgeny-boger commented
примерно понятно. А как мы будем это добавлять в других потребителей: wb-mqtt-db, мосты, wb-rules?
Как там будет работать?

2022-02-11 12:14 UTC, KraPete commented
> примерно понятно. А как мы будем это добавлять в других потребителей: wb-mqtt-db, мосты, wb-rules? Как там будет работать?

Для них сейчас ничего не изменится. db только значение использует.
Мосты можно посмотреть и добавить в них единицы измерения, если протоколы с той сторону позволяют.
wb-rules - не знаю, надо ли там что-то дорабатывать?
Вообще это же больше надо было тем, кто хотел отображение единиц измерения в homeui.

2022-02-14 09:39 UTC, KraPete commented
Немного обсудили. Денлаем units для value только. Значение отправляем в основных единицах. Т.е. 20 мА = 0.02, units = A, units_power = -3. Старые типы шлём как раньше, без units. Остаётся вопрос с м^3 или км/ч, м/с.

2022-02-15 14:11 UTC, KraPete commented
Сделал, как обсудили. Убрал unitsPower

2022-02-17 15:51 UTC, webconn commented
Ещё ничего не написано про:
 - допустимые символы в `units` (что это должна быть ASCII-строка);
 - что `units` поддерживается для типов `value`

2022-02-17 15:52 UTC, webconn commented on conventions.md
> +    "type": "switch",
Кстати, сам пример странный, какой смысл делать `switch` с ваттами )

2022-02-21 08:18 UTC, webconn commented on app/scripts/i18n/units/ru.json
> +        "hour": "час",
Тут надо тоже `hour` на `h` теперь поменять

2022-02-21 09:49 UTC, webconn commented on app/scripts/i18n/units/ru.json
> +        "h": "час",
Ну и в русском варианте уже тогда "ч" оставить :)

2022-02-21 10:55 UTC, webconn approved these changes

2022-02-21 12:00 UTC, merged