Добавил логи к конфигуратору настроек
wirenboard/homeui pull request #308
Opened 2022-03-06 00:03 UTC by olddeda

2022-03-14 05:11 UTC, KraPete commented
@olddeda Может, сделать директивой или компонентом? Сейчас выходит, что у нас в двух местах идентичный большой кусок кода. Хотелось бы как-то переиспользовать его.

2022-03-14 05:13 UTC, KraPete requested changes

2022-03-14 05:13 UTC, KraPete commented on app/scripts/i18n/configurations/ru.json
> +            "normal": "Логи",
Яша был против слова "логи". Может, что-то типа "журнал запуска"

2022-03-14 13:47 UTC, olddeda commented
> @olddeda Может, сделать директивой или компонентом? Сейчас выходит, что у нас в двух местах идентичный большой кусок кода. Хотелось бы как-то переиспользовать его.

Попробую что нибудь придумать

2022-03-18 15:40 UTC, webconn commented
Тут надо ещё увеличить версию deb-пакета, для этого используй утилиту `dch` из пакета `devscripts`. И не забывай перезапрашивать ревью, если правки готовы

2022-03-31 11:20 UTC, KraPete commented on app/scripts/controllers/configController.js
> +    loadBoots() {
Зачем это тут вообще надо? Нам же всегда надо последние данные. Можно вообще не указывать хэш загрузки.

2022-04-11 13:12 UTC, olddeda commented on app/scripts/controllers/configController.js
> +    loadBoots() {
Тут по задумке пока не сохранили показываются предыдущие логи, а после сохранения как раз уже только новые

2022-04-11 13:39 UTC, KraPete commented on app/scripts/controllers/configController.js
> +    loadBoots() {
Я не про то. `boots` - это сеансы включения контроллера, а не запуска сервиса.
`this.scope.logsService.selectedBoot` можно вообще `undefined` оставить, это буле означать, что надо данные с последней загрузки контроллера.

2022-04-11 13:40 UTC, olddeda commented on app/scripts/controllers/configController.js
> +    loadBoots() {
А, понял, уберу тогда

2022-04-11 15:00 UTC, webconn commented
Попробовал позапускать у себя на контроллере, хочу дать обратную связь по UX.

1. Огромная синяя полоска в интерфейсе не читается как штука, на которую можно нажать (моё субъективное имхо)
![image](https://user-images.githubusercontent.com/1550335/162763265-135a38ff-4b30-404c-9947-488dd32c90fa.png)

2. Если возникли ошибки при запуске, надо внимательно читать, что написано в этой синей полоске, есть риск не заметить:
![image](https://user-images.githubusercontent.com/1550335/162765285-37899b2e-f586-41f1-b315-e2433203b57f.png)

3. Лично мне не нравится, что этот список логов растёт без скролла по мере работы. Если в том же serial включить debug, лог разрастётся довольно быстро и страницу придётся скроллить.

4. Неопрятно выглядит то, что логи берутся по времени, а не для отдельного запуска сервиса. Из-за этого могут проглотиться логи из начала работы. Но это вопрос больше к нынешнему API, оно по-другому не умеет сейчас. Думаю, тут надо будет добавить в wb-mqtt-logs возможность отфильтровать по ID запуска (есть такая фича в systemd), а confed по событию сохранения должен уметь этот ID возвращать. В общем, весь этот пункт пока скорее как планы-фантазии, а не про этот PR.

@wb-adegtyarev может у тебя есть идеи, как организовать логи посимпатичней?

![image](https://user-images.githubusercontent.com/1550335/162768171-addcaa5c-87a2-4f78-905e-000e2b206031.png)

2022-04-11 15:19 UTC, olddeda commented
> > Высота растет до определенного размера, дальше внутри появляется скролл
> 
> У меня добиться этого не получилось, включил debug в serial и логи размотало на несколько экранов

понял, проверю почему так

2022-04-11 15:50 UTC, olddeda commented
> > > Высота растет до определенного размера, дальше внутри появляется скролл
> > 
> > 
> > У меня добиться этого не получилось, включил debug в serial и логи размотало на несколько экранов
> 
> странный баг, у меня в Хроме и Safari все норм, а какой браузер?

Мне кажется у тебя стили закешировались и не применились новые

2022-04-11 19:53 UTC, webconn commented
> Мне кажется у тебя стили закешировались и не применились новые

Firefox 91 :)
Ctrl-F5 нажимал, не помогло

2022-04-12 13:43 UTC, olddeda commented
> > Мне кажется у тебя стили закешировались и не применились новые
> 
> Firefox 91 :) Ctrl-F5 нажимал, не помогло

Да, в firefox другое поведение у css, поправил, залил фикс

2022-04-12 14:42 UTC, webconn reviewed
В firefox починилось, спасибо!
Пока ещё не всё отсмотрел, но есть несколько фундаментальных вопросов, напишу прямо сейчас и продолжу ревью

2022-04-12 14:42 UTC, webconn commented on app/scripts/i18n/configurations/en.json
> +            "error": "Has errors",
В интерфейсе выглядит непонятно, где ошибки. Можно по логике догадаться, что если тут написано про ошибку, то надо конфиг править, но это не всегда так. Хочется фразу в духе "сервис запустился с ошибками" (тоже нечестно, мог и не запуститься), или "Журнал запуска (есть ошибки)". Касается и английской, и русской локалей

2022-04-12 14:42 UTC, webconn commented on app/scripts/i18n/configurations/en.json
> +            "empty": "List is empty"
Не список же. Сюда бы лучше сообщение "сохраните конфиг, чтобы увидеть логи запуска"

2022-04-12 14:42 UTC, webconn commented on debian/changelog
> +  * Configs log
`Service logs viewer is added to the config editor`

2022-04-12 14:42 UTC, webconn commented on app/scripts/controllers/configController.js
> +        $scope.logsService = LogsService;
Общий вопрос - а значит ли это, и то, что в html все обращаются к `logsService`, что у нас `LogsService` по сути синглтон? Не сломается ли что-нибудь, если мы захотим два виджета загрузки логов на странице?

2022-04-12 19:03 UTC, webconn reviewed
Посмотрел ещё, остался только logsService, но про него всё ещё фундаментальный вопрос насчёт его синглтоновости

2022-04-12 19:03 UTC, webconn commented on app/views/config.html
> +                    <div id="logs-wrapper" ng-cloak ng-show="!logsService.waitBootsAndServices">
Вот именно в этом месте хотелось бы увидеть отдельный виджет, который потом можно было бы встроить куда-нибудь ещё, в те же дашборды. По сути тот же самый, что сейчас здесь получился.

2022-04-12 19:36 UTC, olddeda commented on app/scripts/controllers/configController.js
> +        $scope.logsService = LogsService;
Он синглтон да. В будущем если будет задача два на одной странице будем думать

2022-04-12 19:37 UTC, olddeda commented on app/scripts/i18n/configurations/en.json
> +            "error": "Has errors",
Там будет красный фон и надпись белым, я показывал же предварительно как будет выглядеть. Тогда подтвердили пример и я так и сделал

2022-04-12 19:38 UTC, olddeda commented on app/scripts/i18n/configurations/en.json
> +            "empty": "List is empty"
Лучше дать мне названия правильные, я внесу

2022-04-12 19:39 UTC, olddeda commented on app/scripts/controllers/configController.js
> +                .then((r) => {
У меня автоформатирование стоит,  да и по сути а коде применяется в разных местах разные принципы форматирования, нужно приводить к одному

2022-04-12 19:40 UTC, olddeda commented on app/views/config.html
> +                    <div id="logs-wrapper" ng-cloak ng-show="!logsService.waitBootsAndServices">
Предлагаю это делать по месту, когда это станет необходимо

2022-04-12 19:41 UTC, olddeda commented on app/scripts/controllers/logsController.js
> +                    .map((l) =>
Форматер к сожалению у меня такой, попробую с ним что то сделать

2022-04-12 19:41 UTC, olddeda commented on app/scripts/controllers/logsController.js
> +                    .map((l) =>
Это происходит когда длина строки больше рекомендуемой

2022-04-12 19:43 UTC, olddeda commented on app/scripts/controllers/logsController.js
> +                desc: undefined,
По мне совершенно бессмысленные комментарии, комментарий ради комментария. С таким подходом можно на каждой строчке их делать. Я больше отношусь к тому что если в коде необходим комментарий то код был плохо написан

2022-04-12 19:50 UTC, webconn commented on app/scripts/i18n/configurations/en.json
> +            "error": "Has errors",
Ну так при ошибке в интерфейсе тоже выводится как что-то красное сверху. Это вопрос про UX, тут стоит пособирать мнения хотя бы внутри компании, я могу переоценивать важность этой надписи

2022-04-12 19:51 UTC, webconn commented on app/scripts/i18n/configurations/en.json
> +            "empty": "List is empty"
`Press "Save" to see service launch log`

2022-04-12 19:53 UTC, webconn commented on app/scripts/controllers/logsController.js
> +                desc: undefined,
То, что код тут просит рефакторинга везде - честная правда. Бессмысленные комментарии надо _не писать_ всеми правдами и неправдами, а не просто так удалять существующие, читаемость кода ведь никак не улучшилась от его удаления

2022-04-12 20:05 UTC, olddeda commented on app/scripts/controllers/logsController.js
> +                desc: undefined,
Добро!

2022-04-12 20:07 UTC, olddeda commented on app/scripts/i18n/configurations/en.json
> +            "error": "Has errors",
Окей, а то честно пока что то других вариантов отображения не придумывается

2022-04-12 20:07 UTC, olddeda commented on app/scripts/i18n/configurations/en.json
> +            "empty": "List is empty"
Спасибо, заменю

2025-06-20 12:08 UTC, vdromanov commented
активности нет - закрываю

2025-06-20 12:08 UTC, closed without merging