Support fullscreen mode
wirenboard/homeui pull request #318
Opened 2022-05-05 14:44 UTC by olddeda

2022-05-06 03:05 UTC, KraPete commented
Конечно, это всё жуткий костыль, любой "хакер" вернёт эти панельки назад. Но в текущей постановке задачи, думаю, решение вполне адекватное.

2022-05-06 03:06 UTC, KraPete requested changes

2022-05-06 03:06 UTC, KraPete commented on debian/changelog
> +  * Support fullscreen mode
Можешь написать тут ещё как должен выглядеть URL?
И ещё расшифровку, что такое fullscreen.

2022-05-24 11:15 UTC, webconn commented
@olddeda пинг

2022-05-27 03:54 UTC, KraPete approved these changes

2022-05-27 08:40 UTC, webconn approved these changes

2022-05-30 18:21 UTC, merged