fwupdate: fix overlapping of wb-watch-update's status
wirenboard/homeui pull request #341
Opened 2022-07-11 11:21 UTC by vdromanov

Ноги растут из новой загрузки fwupdate (через cgi вместо модуля nginx).
Wb-watch-update видит появление файла (и шлёт через mqtt ругательства, если надо) чуть раньше, чем отрабатывает загружающий cgi-скрипт => ругательства от wb-watch-upfate (например, на некорректный файл fwupdate) перекрываются на фронте сообщением "Ок, файл загружен".
Подозреваю, раньше работало, т.к. было просто чуть быстрее.

поднимали вопрос на синке - решили посмотреть во фронт, т.к. с бека простого решения нет
решение - не перерисовываем статус, если от wb-watch-update что-то прилетело
проверил, что всё выглядит и работает, как раньше

2022-07-22 12:18 UTC, webconn requested changes
Переменную предлагаю переименовать, а вот с логикой не знаю. Наверное, лучше стало, но у меня получалось добиться ситуаций, когда загружаешь небольшой файл (не наш фит), и в итоге оно показывает, что загрузка успешна, и не показывает ошибку (хотя иногда видно, что она на мгновение появляется).

Не думаю, что надо прямо сейчас дебажить, можно полчаса потратить на это. Не получится - и ладно

2022-07-22 12:18 UTC, webconn commented on app/scripts/controllers/firmwareController.js
> +      $scope.mqttStatusHasSet = false;
По-моему этот флаг стоит сбрасывать только при нажатии кнопки Done (если подразумевается, что всё остальное время будет показываться окошко с логами mqtt)

2022-07-22 12:18 UTC, webconn commented on app/scripts/controllers/firmwareController.js
> +        $scope.mqttStatusHasSet = false;
И вот это тоже лишнее, кмк

2022-07-25 15:57 UTC, vdromanov commented on app/scripts/controllers/firmwareController.js
> +    $scope.mqttStatusHasSet = false;  // to prevent overlapping from $scope.upload
готово

2022-07-26 10:24 UTC, webconn approved these changes

2022-07-26 14:45 UTC, merged