max_records parameter is added to wb-mqtt-db request
wirenboard/homeui pull request #344
Opened 2022-07-14 07:01 UTC by KraPete

Работает совместно с https://github.com/wirenboard/wb-mqtt-db/pull/27

Было
![изображение](https://user-images.githubusercontent.com/86825564/178921148-d66b1bdc-48ca-4a38-b533-f5f80741f6e9.png)

Обновил запрос и установил новую wb-mqtt-db, стало
![изображение](https://user-images.githubusercontent.com/86825564/178921410-27e7079f-8209-446e-ba57-35c5e54bf5ee.png)

2022-07-15 13:28 UTC, webconn commented
А со старыми версиями wb-mqtt-db это работает нормально? запрашивает по старой модели?

2022-07-21 07:34 UTC, KraPete commented
![изображение](https://user-images.githubusercontent.com/86825564/180156472-ed729bba-3e21-4ee0-acf1-0d71ceed68f8.png)

Сделал вывод мс для дискретных сигналов. Для остальных нет смысла, т.к. они пишутся с минимальным шагом в секунду.

2022-07-21 18:00 UTC, webconn commented on app/scripts/controllers/historyController.js
> +        params.max_records = this.historyMaxPoints
Допиши сюда, что `max_records` приоритетней, и в будущем `min_interval` будет deprecated

2022-07-21 18:05 UTC, webconn commented on app/scripts/controllers/historyController.js
> +        params.max_records = this.historyMaxPoints
Кстати, тут хотелось бы не `historyMaxPoints`, а что-нибудь более осмысленное, например, ширину виджета. `historyMaxPoints` у нас захардкожена как константа и представляет собой скорее защитный лимит, как я понимаю

2022-07-21 18:11 UTC, webconn commented on app/scripts/controllers/historyController.js
> +            if (d.getMilliseconds()) {
Люблю я неявные проверки на ноль :)
Сначала пошёл искать, может ли `getMilliseconds()` вернуть какой-нибудь `null`, а потом каааак понял.

Ну и, кстати, будет некрасиво выглядеть, если какое-нибудь дискретное событие случайно попадёт в 0 по миллисекундам. Лучше уж вообще всё единообразно выводить, ну пусть там будут нолики у всех, или наоборот, всегда только секунды.

Вроде как можно селектор в шаблон добавить по `hasBooleanValues`? Если это слишком сложно, то можно оставить как есть

2022-07-22 05:46 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +        params.max_records = this.historyMaxPoints
Написал

2022-07-22 06:26 UTC, KraPete commented on app/scripts/controllers/historyController.js
> +        params.max_records = this.historyMaxPoints
Сделал

2022-07-22 17:08 UTC, webconn requested changes
Давай `$timeout` ещё влепим в зависимости `HistoryCtrl`, и аппрувим

2022-07-25 02:18 UTC, KraPete commented on app/scripts/controllers/historyController.js
>          var chunks = this.handleData.splitDate(this.startDate,this.endDate,this.CHUNK_INTERVAL+1);
Да, там жесть какая-то.

2022-07-25 02:18 UTC, KraPete commented
> Давай `$timeout` ещё влепим в зависимости `HistoryCtrl`, и аппрувим

Зачем? Тамоно через `$injector` сделано. Одно и то же

2022-07-25 07:27 UTC, webconn approved these changes
Проверил, вроде работает. Не понял, как должна помочь магия с подключением `$timeout` через `$injector`, мне какая-то абстрактная чуйка подсказывает, что при подключении через аргументы оно должно откладываться до готовности `$timeout` и за счёт этого выезжать, а посреди вызова конструктора... Документацию за 5 минут про это найти не смог. Если будет ломаться - полезем туда ещё раз

2022-07-25 12:44 UTC, evgeny-boger commented on app/scripts/controllers/historyController.js
>          var chunks = this.handleData.splitDate(this.startDate,this.endDate,this.CHUNK_INTERVAL+1);
там я в соседнем PR эту дрянь выкидывал же

2022-07-25 12:45 UTC, evgeny-boger approved these changes

2022-07-25 15:24 UTC, webconn commented on app/scripts/controllers/historyController.js
>          var chunks = this.handleData.splitDate(this.startDate,this.endDate,this.CHUNK_INTERVAL+1);
Который драфт, с замечаниями по ревью и не обновлялся несколько недель (читай - забыт :( )

2022-07-26 04:04 UTC, merged