Add display precision
wirenboard/homeui pull request #368
Opened 2022-11-16 14:37 UTC by ekateluv

Ребейз https://github.com/wirenboard/homeui/pull/366

2022-11-16 15:07 UTC, KraPete commented on app/scripts/directives/valuecell.html
> +    <span style="display:none">{{ digits = cell.step.toString().split('.')[1].length}}</span>
Вся эта разметка попадёт на страницу только ради внутренних вычислений. Думаю, надо это всё убрать в контроллер.

2022-11-20 10:25 UTC, KraPete requested changes

2022-11-20 10:25 UTC, KraPete commented on app/scripts/directives/valuecell.js
> +    }
Давай, что-то возвращать тут, например, пустую строку

2022-11-20 10:25 UTC, KraPete commented on app/scripts/directives/valuecell.html
> +    <span class="decimal">{{vCtrl.getFractionalValue(cell)}}</span>
Тут мы стали строку возвращать, было бы круто сразу с точкой впереди, тогда и span первый не нужен.

2022-11-20 10:25 UTC, KraPete commented on app/scripts/directives/valuecell.js
> +    }
Давай, тут тоже что-то возвращать, например, пустую строку

2022-11-20 10:25 UTC, KraPete commented on debian/changelog
> +  * Add value display accuracy if /meta/precision exists
Мы обозвали топики в `/meta` - `deprecated`. Можно просто написать, что если контрол отдаёт точность, то она используется для заполнения нулями. Сейчас тут написано так, что не ясно, что происходит.

2022-11-22 04:44 UTC, KraPete commented on app/scripts/directives/valuecell.html
> +    <span class="decimal">{{vCtrl.getFractionalValue(cell)}}</span>
Можно картинку того как это выглядит? Сколько цифр после запятой не вылазят за границы карточки?

2022-11-22 08:21 UTC, ekateluv commented on app/scripts/directives/valuecell.html
> +    <span class="decimal">{{vCtrl.getFractionalValue(cell)}}</span>
![Снимок экрана от 2022-11-22 11-08-50](https://user-images.githubusercontent.com/97599621/203260086-6047c6b8-29af-4cae-8a3f-b0fe4750c97a.png)
![Снимок экрана от 2022-11-22 11-09-15](https://user-images.githubusercontent.com/97599621/203260091-236d94fb-b109-447f-a4fd-43864e1e9f32.png)
![Снимок экрана от 2022-11-22 11-10-09](https://user-images.githubusercontent.com/97599621/203260095-5a531005-84ba-4daa-9874-19fc12eeb0d5.png)
Смотри на А1. Первый скрин без точности, второй 0.01, третий 0.0000001 - помещается только четыре разряда.

2022-11-22 08:36 UTC, ekateluv commented on app/scripts/directives/valuecell.html
> +    <span class="decimal">{{vCtrl.getFractionalValue(cell)}}</span>
Есть вот такой скриншот. Раньше было по пять
![изображение](https://user-images.githubusercontent.com/97599621/203265142-10c1efbf-ec2f-4cc3-a3d2-6d84f15a456a.png)

2022-11-22 08:40 UTC, KraPete commented on app/scripts/directives/valuecell.html
> +    <span class="decimal">{{vCtrl.getFractionalValue(cell)}}</span>
Тогда надо css править, чтоб снова 5 было

2022-11-22 12:47 UTC, ekateluv commented on app/scripts/directives/valuecell.html
> +    <span class="decimal">{{vCtrl.getFractionalValue(cell)}}</span>
![изображение](https://user-images.githubusercontent.com/97599621/203317639-a5bf607d-3add-4b1b-ba44-31a98a24e77c.png)

2022-11-22 12:57 UTC, KraPete approved these changes

2022-11-22 15:14 UTC, webconn reviewed
@KraPete как думаешь?

2022-11-22 15:14 UTC, webconn commented on app/styles/css/new.css
> +    width: 47px;
Кстати, в CSS есть специальный юнит `ch`, который соответствует ширине символа `0` - это ж то, что нам нужно? Может, его использовать? В chrome поддержка почти 10 лет назад въехала

2022-11-23 09:49 UTC, KraPete commented on app/styles/css/new.css
> +    width: 47px;
Да, так, наверное, лучше будет, чем в пикселях

2022-11-23 10:15 UTC, webconn approved these changes

2022-11-23 11:07 UTC, ekateluv commented
Обновился мастер, сделала ребейз еще раз https://github.com/wirenboard/homeui/pull/372

2022-11-23 11:07 UTC, closed without merging