Add advert for upgrade via FIT
wirenboard/homeui pull request #377
Opened 2022-12-04 13:39 UTC by sikmir

2022-12-05 04:58 UTC, KraPete requested changes

2022-12-05 04:58 UTC, KraPete commented on app/scripts/i18n/app/en.json
> +        "bullseyeNotice3": " or download FIT firmware image from http://fw-releases.wirenboard.com/?prefix=fit_image/ and update via the web interface by visiting Settings → System"
Давай, ссылку ссылкой сделаем. Например, чтобы `FIT firmware image` было ссылкой. `Settings -> System`, тоже можно ссылкой сделать.

2022-12-05 07:25 UTC, sikmir commented on app/scripts/i18n/app/en.json
> +        "bullseyeNotice3": " or download FIT firmware image from http://fw-releases.wirenboard.com/?prefix=fit_image/ and update via the web interface by visiting Settings → System"
добавил

2022-12-05 10:02 UTC, KraPete requested changes
![image](https://user-images.githubusercontent.com/86825564/205609270-e43c0d8e-1db2-4936-93ea-ad28002accd6.png)

2022-12-06 04:33 UTC, KraPete approved these changes

2022-12-06 05:39 UTC, merged