Add ESLint and Prettier configs
wirenboard/homeui pull request #379
Opened 2022-12-28 07:47 UTC by KraPete

2022-12-28 07:49 UTC, webconn reviewed
А что тут с changelog случилось?

2022-12-28 07:55 UTC, webconn requested changes
Хочу ещё тут в README или где-то рядом инструкцию о том, как этим пользоваться (хотя бы в виде ссылки на пример настройки vscode и как применить автоформат через консоль)

2022-12-28 07:55 UTC, webconn commented on debian/changelog
> + -- Petr Krasnoshchekov <petr.krasnoshchekov@wirenboard.com> Wed, 28 Dec 2022 12:45:36 +0500
Опять что-то не то.

Я правильно понимаю, что это автоформатирование случилось? Может, сразу файл вписать в исключения где-нибудь?

2022-12-28 08:00 UTC, sikmir commented on package.json
> +    "eslint": "^8.30.0",
Для `devDependencies` не критично, а вот для `dependencies` может пинить конкретнкую версию, а не `^...`? А то при очередном обновлении может что-то сломаться.

2022-12-28 08:26 UTC, KraPete commented on package.json
> +    "eslint": "^8.30.0",
По идее же есть `package-lock.json`, но мы его нигде не храним

2022-12-28 08:29 UTC, KraPete commented on debian/changelog
> + -- Petr Krasnoshchekov <petr.krasnoshchekov@wirenboard.com> Wed, 28 Dec 2022 12:45:36 +0500
Я руками скопировал это из прошлого коммита. А форматирование сделал в vscode только для js, было глобальное

2022-12-28 08:30 UTC, sikmir commented on package.json
> +    "eslint": "^8.30.0",
Ну вот либо lock хранить, так даже лучше. Просто сейчас пакет foo 1.0.1 может обновится до foo 1.0.2 при этом что-от сломать и отловить в чем причина будет сложно, так как один и тот же код homeui собранный в разное время будет вести себя по разному.

2022-12-28 08:36 UTC, sikmir commented on debian/changelog
> -wb-mqtt-homeui (2.50.0) stable; urgency=medium
Может 2.49.2? Функциональных изменений же нет.

2022-12-28 08:39 UTC, sikmir approved these changes

2022-12-28 08:40 UTC, sikmir commented on debian/changelog
> +wb-mqtt-homeui (2.50.1) stable; urgency=medium
2.50.0 удалилось.

2022-12-28 10:40 UTC, KraPete commented on debian/changelog
> +wb-mqtt-homeui (2.50.1) stable; urgency=medium
Вернул

2022-12-28 10:47 UTC, webconn reviewed
Всё ещё хочу инструкцию

2022-12-28 10:47 UTC, webconn commented on debian/changelog
> + wb-mqtt-homeui (2.50.0) stable; urgency=medium
Тут пробел почему-то появился :(

2022-12-28 10:48 UTC, KraPete commented on package.json
> +    "eslint": "^8.30.0",
Добавил `package-lock.json`

2022-12-28 10:50 UTC, KraPete commented on debian/changelog
> + wb-mqtt-homeui (2.50.0) stable; urgency=medium
Исправил

2023-01-02 17:20 UTC, sikmir commented on package.json
> +    "eslint": "^8.30.0",
Кстати вместо `npm` можно использовать `yarn`, он пошустрее зависимости вытягивает (вроде как из-за того что умеет в параллельность):
```sh
$ time npm install
...
________________________________________________________
Executed in  310.96 secs    fish           external
   usr time  189.50 secs    0.34 millis  189.50 secs
   sys time   22.12 secs    1.14 millis   22.12 secs
$ rm -fr node_modules
$ time yarn
...
________________________________________________________
Executed in  197.41 secs    fish           external
   usr time  175.62 secs    0.27 millis  175.62 secs
   sys time   26.81 secs    1.51 millis   26.81 secs
```
В остальном ничего не меняется. Только вместо `npm install` -> `yarn`, вместо `npm run build` -> `yarn build` и вместо `package-lock.json` -> `yarn.lock`.

2023-01-02 20:39 UTC, sikmir commented on package.json
> +    "eslint-plugin-prettier": "^4.2.1",
Ругается:
`warning " > eslint-plugin-prettier@4.2.1" has unmet peer dependency "prettier@>=2.0.0".`
Фикс (https://github.com/prettier/eslint-plugin-prettier#installation):
`npm install --save-dev --save-exact prettier`

2023-06-06 04:25 UTC, KraPete commented
Перенёс в https://github.com/wirenboard/codestyle/pull/48

2023-06-06 04:25 UTC, closed without merging