json-editor: array tabs highlighting support + alerts in editor
wirenboard/homeui pull request #381
Opened 2023-01-10 11:22 UTC by webconn

This is used in network connections editor to show legacy items that should be removed.

![Screenshot_20230110_171640](https://user-images.githubusercontent.com/1550335/211537367-d205c8d2-e599-49c1-a72e-ba88e6251fe5.png)

![Screenshot_20230110_171718](https://user-images.githubusercontent.com/1550335/211537409-0349153f-7e75-4b13-a179-a98b7c469090.png)

2023-01-10 12:47 UTC, lostpoint-ru approved these changes

2023-01-11 06:14 UTC, KraPete requested changes

2023-01-11 06:14 UTC, KraPete commented on app/scripts/components/json-editor/wb-bootstrap3-iconlib.js
> +  warning: 'fas fa-exclamation-triangle'
А чем из бутстрапа `glyphicon glyphicon-exclamation-sign` не угодил? Он у нас везде в интерфейсе используется

2023-01-11 06:40 UTC, webconn commented on app/scripts/components/json-editor/wb-bootstrap3-iconlib.js
> +  warning: 'fas fa-exclamation-triangle'
А это я проглядел просто, уберу

2023-01-11 07:53 UTC, webconn commented on app/scripts/components/json-editor/collapsible-multiple-editor.js
> +        updateCustomWarning(editor) {
Попробовал, валидатор со стороны confed не очень был этому рад. Не хочу сейчас ради этой фичи патчить ещё и конфед, решили оставить как есть

2023-01-11 08:00 UTC, webconn commented on app/scripts/components/json-editor/wb-bootstrap3-iconlib.js
> +  warning: 'fas fa-exclamation-triangle'
Переделал, стало так
![image](https://user-images.githubusercontent.com/1550335/211750225-c86e4d27-0154-4a84-9b09-a34fd624933a.png)

2023-01-11 08:22 UTC, KraPete approved these changes

2023-01-11 08:27 UTC, merged