Support brute force scanning
wirenboard/homeui pull request #386
Opened 2023-01-31 14:14 UTC by sikmir

Помечает устройства найденные через быстрое сканирование (то есть версия прошивки устройства поддерживает быстрое сканирование):
<img width="213" alt="Näyttökuva 2023-1-31 kello 17 09 27" src="https://user-images.githubusercontent.com/688044/215783355-4d479a95-e716-403f-ab4e-45a6f75afb9d.png">
<img width="137" alt="Näyttökuva 2023-1-31 kello 17 10 14" src="https://user-images.githubusercontent.com/688044/215783368-2a56e510-8fb7-4f2c-8fb8-19421965bded.png">

2023-01-31 14:47 UTC, KraPete requested changes

2023-01-31 14:47 UTC, KraPete commented on app/scripts/react-directives/scan/desktop.jsx
> +  let version = props.version;
Чё-то много стало одинакового кода. Стоит вынести это в отдельный компонент и переиспользовать

2023-01-31 16:59 UTC, sikmir commented on app/scripts/react-directives/scan/desktop.jsx
> +  let version = props.version;
вынес

2023-02-01 05:51 UTC, KraPete requested changes

2023-02-01 05:51 UTC, KraPete commented on app/scripts/i18n/react/locales/en/translations.json
> +         "scanning-stop": "Press \"Stop\", if all devices are found, or wait for completion.",
В других сообщениях нет точки в конце

2023-02-01 05:51 UTC, KraPete commented on app/scripts/react-directives/scan/scan.js
> +            scanning_port: observable,
https://airbnb.io/javascript/#naming--camelCase

2023-02-01 05:51 UTC, KraPete commented on app/scripts/i18n/react/locales/ru/translations.json
> +         "scanning-stop": "Нажмите \"Стоп\", если все устройства уже найдены, или дождитесь завершения.",
Тут тоже точка

2023-02-01 05:51 UTC, KraPete commented on app/scripts/react-directives/scan/common.jsx
> +function FirmwareVersionWithLabels({version, available_fw, ext_support}) {
Тут тоже стоит назвать параметры в camel case

2023-02-01 05:51 UTC, KraPete commented on app/scripts/react-directives/scan/common.jsx
> +function FirmwareVersionWithLabels({version, available_fw, ext_support}) {
Может, так? Кажется, нагляднее
```jsx
<>
{version}
{available_fw && (t('device-manager.labels.available') + ' ' + available_fw)}
{ext_support && <span class="glyphicon glyphicon-flash"></span>}
</>
```

2023-02-01 05:51 UTC, KraPete commented on app/scripts/react-directives/scan/deviceManager.jsx
> +      <InfoMessage msg={t('device-manager.labels.scanning') + " " + port + " ..."}/>
Давай, порт параметром в функцию перевода сделаем

2023-02-01 05:53 UTC, KraPete commented on app/scripts/react-directives/scan/common.jsx
> +function FirmwareVersionWithLabels({version, available_fw, ext_support}) {
Хорошо бы ещё available_fw передавать параметром в перевод

2023-02-01 06:48 UTC, sikmir commented on app/scripts/i18n/react/locales/en/translations.json
> +         "scanning-stop": "Press \"Stop\", if all devices are found, or wait for completion.",
убрал

2023-02-01 06:48 UTC, sikmir commented on app/scripts/react-directives/scan/scan.js
> +            scanning_port: observable,
поправил

2023-02-01 06:48 UTC, sikmir commented on app/scripts/i18n/react/locales/ru/translations.json
> +         "scanning-stop": "Нажмите \"Стоп\", если все устройства уже найдены, или дождитесь завершения.",
убрал

2023-02-01 06:49 UTC, sikmir commented on app/scripts/react-directives/scan/common.jsx
> +function FirmwareVersionWithLabels({version, available_fw, ext_support}) {
готово

2023-02-01 06:49 UTC, sikmir commented on app/scripts/react-directives/scan/deviceManager.jsx
> +      <InfoMessage msg={t('device-manager.labels.scanning') + " " + port + " ..."}/>
готово

2023-02-01 07:31 UTC, KraPete approved these changes

2023-02-01 11:19 UTC, merged