Add hint about scanning via extended modbus
wirenboard/homeui pull request #387
Opened 2023-02-01 21:37 UTC by sikmir

2023-02-02 07:14 UTC, ekateluv commented on app/scripts/i18n/react/locales/en/translations.json
> +         "extended-modbus": "This device was found by scanning via Extended Modbus protocol"
Может быть стоит обсудить внтури компании, как мы все таки это называем? Кто то говорит расширенный модбас, кто то говорит быстрый. Если и то и другое просочится в документы/интерфейс то клиенты могут начать думать что это что то разное

2023-02-02 09:37 UTC, sikmir commented on app/scripts/i18n/react/locales/en/translations.json
> +         "extended-modbus": "This device was found by scanning via Extended Modbus protocol"
Спросил в чатике документации, пока сошлись на "WB Modbus".

2023-02-03 08:59 UTC, KraPete requested changes

2023-02-03 08:59 UTC, KraPete commented on debian/changelog
> +  * Add hint about scanning via extended modbus
WB Modbus?

2023-02-03 09:02 UTC, sikmir commented on debian/changelog
> +  * Add hint about scanning via extended modbus
поправил

2023-02-03 09:56 UTC, KraPete approved these changes

2023-02-03 09:56 UTC, merged