Scanner stop button
wirenboard/homeui pull request #389
Opened 2023-02-03 17:33 UTC by webconn

Сделал кнопку Stop scan, вместе с этим подправил логику, в какие моменты кнопка остаётся неактивной (от момента нажатия до ответа сервиса о том, что сканирование реально началось или закончилось).

Краевой случай - сканирование запустили или остановили из другой вкладки или из консоли. В этом случае кнопка остаётся активной. Расписал это всё в тестах.

2023-02-04 10:30 UTC, sikmir commented
Backend for testing: https://github.com/wirenboard/wb-device-manager/pull/20

2023-02-04 10:36 UTC, sikmir commented
Вот это надо раскомментировать: https://github.com/wirenboard/homeui/blob/8eb89566f5153fab3222300588e98cb314e178dd/app/scripts/react-directives/scan/deviceManager.jsx#L92

2023-02-06 04:29 UTC, KraPete requested changes
Мы обсуждали с Вовой работу остановки сканированияю Она - асинхронная. Т.е. реально факт остановки надо проверять по статусу. У тебя это учитывается?

2023-02-06 04:29 UTC, KraPete commented on app/scripts/services/deviceManagerProxy.js
> +    "Scan", "Stop"
На бэке у нас теперь `Start` вместо `Scan`.

2023-02-06 04:29 UTC, KraPete commented on app/scripts/react-directives/scan/scan.js
> +    requestedScanning = undefined
Мне не нравится, когда у переменной с семантикой флага, есть используемое состояние `undefined`. Это какой-то недо-enum. Ещё и комментариев про логику работы нет.

2023-02-06 04:49 UTC, webconn commented on app/scripts/react-directives/scan/scan.js
> +    requestedScanning = undefined
Согласен, могу сделать аккуратней. Но зато в задействованном состоянии (не undefined) очень красивые сравнения в шаблоне получаются

2023-02-06 04:49 UTC, webconn commented
> Мы обсуждали с Вовой работу остановки сканированияю Она - асинхронная. Т.е. реально факт остановки надо проверять по статусу. У тебя это учитывается?

Да, я предлагаю оставить сканирование, только если в статусе false, и наоборот

2023-02-06 07:51 UTC, webconn commented on app/scripts/services/deviceManagerProxy.js
> +    "Scan", "Stop"
Починил, и добавил конфликтов

2023-02-06 07:51 UTC, webconn commented on app/scripts/react-directives/scan/scan.js
> +    requestedScanning = undefined
Переделал на енум, стало понятней?

2023-02-06 07:58 UTC, sikmir commented on app/scripts/react-directives/scan/deviceManager.jsx
> +      {<InfoMessage msg={t('device-manager.labels.scanning-stop')}/>}
{} тоже надо убрать

2023-02-06 08:02 UTC, webconn commented on app/scripts/react-directives/scan/deviceManager.jsx
> +      {<InfoMessage msg={t('device-manager.labels.scanning-stop')}/>}
Готово

2023-02-06 08:06 UTC, sikmir approved these changes

2023-02-06 08:25 UTC, KraPete reviewed
Надо вернуть нормальное сообщение.

2023-02-06 08:40 UTC, webconn commented
> 1. Надо вернуть сообщение
Не относится к этому PR, но решить это стоит. Предлагаю на демо сегодня. Поправить текст - дело нехитрое.

>     2. Если нажать F5 во время сканирования, а потом остановить, то напишет, что сканирование ещё не производилось.

Починил

2023-02-06 08:51 UTC, webconn commented
Выпилил вообще сообщение про прошивки. Казалось бы, сканер теперь работает для всех, потому не нужно принудительно обновлять прошивки. Про быстрое сканирование говорит значок молнии.

2023-02-06 08:51 UTC, KraPete approved these changes

2023-02-06 08:55 UTC, merged