add HMI mode for dashboards
wirenboard/homeui pull request #395
Opened 2023-02-08 06:30 UTC by KraPete

* Add HMI mode for dashboards It can be activated by "hmi" query parameter in URL.
* Add "hmicolor" query parameter to define dashboard background color in HMI mode
* Fullscreen toggle button doesn't hide navigation panels

2023-02-09 06:00 UTC, KraPete commented
![image](https://user-images.githubusercontent.com/86825564/217730657-e87c201e-d29f-4ab2-90cb-64a0616ea421.png)

Теперь в полноэкранном режиметак:

2023-02-10 09:16 UTC, webconn commented
Хочу здесь же тесткейсы про этот режим.

А в мобильной версии оно как-то должно работать? У меня в полноэкранный режим переходит, но в портретной ориентации панель сверху не исчезает, а в альбомной панель сбоку занимает полэкрана

2023-02-10 09:17 UTC, webconn requested changes
Тесткейсы

2023-02-10 10:09 UTC, webconn commented
> В мобильной и не должно исчезать. Надо же как-то иметь доступ к списку панелей. В портретном режиме ширина экрана у тебя, видимо, больше 768, при этом всегда левая панель показывалась, вот и сейчас она показывается.

Не, в портретном оно ведёт себя как ожидаешь от мобильной - панелька сверху (и пусть там и будет).
Мой вопрос был скорее в том, обсуждали ли это поведение или нет

2023-02-10 10:42 UTC, KraPete commented
Значит, у тебя ширины экрана не хватает. А вообще не обсуждали, потому осталось как в обычном режиме. Т.е. если окно уже 768 пикселей, то мобильное отображение, шире - десктопное.

2023-02-10 11:17 UTC, webconn reviewed
Вроде всё хорошо, немного правок предложил в тест-кейсы (не хватило спеллчекера)

2023-02-10 11:17 UTC, webconn commented on app/styles/main.css
> +@media(max-width: 406px) {
От этой магии надо будет избавляться, конечно. Я ещё и не могу это константу найти в бутстрапе

2023-02-10 11:17 UTC, webconn commented on test/scenarios/Fullscreen.md
> +    * В строке барузера добавить к адресу `?hmicolor=red`
```suggestion
    * В строке браузера добавить к адресу `?hmicolor=red`
```

2023-02-10 11:17 UTC, webconn commented on test/scenarios/Fullscreen.md
> +    * В строке барузера добавить к адресу `?hmi&hmicolor=red`
```suggestion
    * В строке браузера добавить к адресу `?hmi&hmicolor=red` или `?hmi&hmicolor=%23FF0000`
```

Это типа пример того, как писать RGB

2023-02-10 11:17 UTC, webconn commented on test/scenarios/Fullscreen.md
> +    * Выполнить п.4. вместо выхода из полноэеранного режима по нажатию кнопки, нажать `esc`
```suggestion
    * Выполнить п.4. вместо выхода из полноэкранного режима по нажатию кнопки, нажать `esc`
```

2023-02-10 11:17 UTC, webconn commented on test/scenarios/Fullscreen.md
> +    * Выполнить п.5. вместо выхода из полноэеранного режима по нажатию кнопки, нажать `esc`
```suggestion
    * Выполнить п.5. вместо выхода из полноэкранного режима по нажатию кнопки, нажать `esc`
```

2023-02-10 11:20 UTC, KraPete commented on app/styles/main.css
> +@media(max-width: 406px) {
Не найдёшь. Это 390 + поля. Там страшный код вокруг

2023-02-10 11:21 UTC, webconn approved these changes

2023-02-10 11:22 UTC, webconn commented
На будущее - можно правки батчами применять, чтобы 4 коммита в CI не летело

2023-02-10 12:18 UTC, merged