Add check connectivity url validating
wirenboard/homeui pull request #423
Opened 2023-04-19 12:23 UTC by ekateluv

Проверяется валидность url. Валидность по пустой строке сделана, чтобы в файл записывалось дефолтное значение. Раньше при пустой строке не записывалось ничего,  нельзя было сбросить существующее значение

2023-04-20 09:24 UTC, webconn requested changes
Мне кажется, помимо подсветки поля красным, надо указывать, что именно с ним не так, а в целом уже хорошо

2023-04-20 09:56 UTC, KraPete commented on app/scripts/react-directives/network-connections/switcherStore.js
> +  if (json.connectivity_check_url == store.connectivityUrl.placeholder){
Почему нельзя просто пустую строку хранить?

2023-04-21 11:42 UTC, ekateluv commented on app/scripts/react-directives/network-connections/switcherStore.js
> +  if (json.connectivity_check_url == store.connectivityUrl.placeholder){
Ну там раньше проверка стояла, что если пустая строка то не записывать ничего
```
  if (store.connectivityUrl.value !== '') {
    res.connectivity_check_url = store.connectivityUrl.value;
```
Плюс потом можно словить гипотетическую ситуацию, что в бэке поменяется дефолтный урл, а тут на фоне будет старый и пользователи будут думать что по умолчанию одно, а фактически другое. Не знаю, насколько это возможно конечно

2023-04-21 12:14 UTC, KraPete commented on app/scripts/react-directives/network-connections/switcherStore.js
> +  if (json.connectivity_check_url == store.connectivityUrl.placeholder){
Тогда надо брать его из схемы

2023-05-02 04:30 UTC, KraPete requested changes
Прогони все изменения через Prettier

2023-05-02 04:30 UTC, KraPete commented on app/scripts/react-directives/network-connections/pageStore.js
> +    this.switcher.setSchema(schema)
Мне не нравится, что сюда передаётся вся схема, а потом где-то внутри выискивается нужное свойство с глубийной в 6 параметров. Сюда надо передавать только нужные параметры.

2023-05-02 04:30 UTC, KraPete commented on app/scripts/i18n/react/locales/en/translations.json
> +         "connectivity-url-error-length": "The minimum number of characters in the URL is ",
У i18n есть возможность использовать переменные для подстановки в перевод. Стоит использовать их здесь и в строке ниже.

2023-05-02 04:30 UTC, KraPete commented on app/scripts/react-directives/network-connections/switcherStore.js
> +        }
Я понимаю, что это JS и тут функция вернёт undefined, если не указан явно return, но не красиво.

2023-05-02 04:30 UTC, KraPete commented on app/scripts/react-directives/network-connections/switcherStore.js
> +          if (value == ""){
Может всё обернуть в
```
if (value !== "") {
....
} 
```
?

2023-05-02 10:34 UTC, ekateluv commented on app/scripts/react-directives/network-connections/pageStore.js
> +    this.switcher.setSchema(schema)
поправлено

2023-05-02 10:34 UTC, ekateluv commented on app/scripts/i18n/react/locales/en/translations.json
> +         "connectivity-url-error-length": "The minimum number of characters in the URL is ",
поправлено

2023-05-02 10:34 UTC, ekateluv commented on app/scripts/react-directives/network-connections/switcherStore.js
> +        }
поправлено

2023-05-02 10:34 UTC, ekateluv commented on app/scripts/react-directives/network-connections/switcherStore.js
> +          if (value == ""){
поправлено

2023-05-02 14:11 UTC, KraPete reviewed
А через Prettier последние правки не прогнали ...

2023-05-02 14:30 UTC, KraPete approved these changes

2023-05-02 14:34 UTC, merged