Feature/60432 enlarge your rootfs
wirenboard/homeui pull request #438
Opened 2023-05-29 15:35 UTC by lostpoint-ru

Правка добавляет в виджет загрузки прошивки флаг "расширить rootfs, если прошивка поддерживает это", который, в случае установки, уходит вместе с файлом в http-запросе на бэкенд.

2023-05-30 05:46 UTC, KraPete requested changes

2023-05-30 05:46 UTC, KraPete commented on app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
> +import React, { useRef, useEffect, useMemo } from 'react';
```suggestion
import React, { useRef, useEffect } from 'react';
```

2023-05-30 05:46 UTC, KraPete commented on app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
> +const UploadEntrypoint  = observer(({store, showModal}) => {
Я бы не просил весь `store` тут, только обработчик изменения состояния чекбокса, тем более что рядом тоже просто обработчик нажатия

2023-05-30 05:46 UTC, KraPete commented on app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
> +            <li className="ng-binding">
Зачем `ng-binding`? Это ж ангуляровский класс

2023-05-30 05:46 UTC, KraPete commented on app/scripts/react-directives/firmware-update/store.js
> +    console.log('expandRootfs', this.expandRootfs);
Остатки дебага?

2023-05-30 05:49 UTC, KraPete commented
В мобильном варианте выглядит странно
![image](https://github.com/wirenboard/homeui/assets/86825564/5d5d3a7e-267b-4b88-bfb9-f46865f44083)

2023-05-30 09:22 UTC, lostpoint-ru commented on app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
> +import React, { useRef, useEffect, useMemo } from 'react';
Это незамеченный пережиток попыток использовать event handler в Uploady. Уберу.

2023-05-30 09:36 UTC, lostpoint-ru commented on app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
> +            <li className="ng-binding">
Скопипастил ради единообразия из соседнего виджета где рутфс скачивается. Уберу.

2023-05-30 09:37 UTC, lostpoint-ru commented on app/scripts/react-directives/firmware-update/store.js
> +    console.log('expandRootfs', this.expandRootfs);
Ага, проглядел.

2023-05-30 10:31 UTC, KraPete requested changes
![image](https://github.com/wirenboard/homeui/assets/86825564/ba60887e-ceaa-48bc-9111-3bfdcf76e9af)

2023-05-31 04:45 UTC, KraPete approved these changes

2023-05-31 08:09 UTC, merged