Feature/61448 react tests
wirenboard/homeui pull request #441
Opened 2023-06-09 10:33 UTC by lostpoint-ru

Убрал, по совету коллег, старые нерабочие тесты, начал обкладывать React-компоненты юнит-тестами на Jest.

2023-06-14 13:20 UTC, webconn reviewed
А у меня тут внезапный вопрос: а старые тесты точно сильно сломаны? Не пробовал их запускать случайно? Может, там что-то просто надо ситуативно поправить и у нас будет больше покрытие

2023-06-14 13:20 UTC, webconn commented on test/react/firmware-update/modal.test.js
> +it('constructor without id', () => {
Тут же тебе тестовый фреймворк подсказывает, как предложение строить :)
```suggestion
it('may be constructed without id', () => {
```

При этом в следующем файле у тебя уже аккуратней с этим

2023-06-14 13:20 UTC, webconn commented on test/react/firmware-update/store.test.js
> +it('on upload start', () => {
Тут и дальше тоже можно объяснить, что тут происходит

2023-06-15 15:57 UTC, sikmir commented
Что-то у меня не взлетели тесты:
```sh
$ npm run test

> homeui-webpack@0.1.0 test
> jest test/react

 FAIL  test/react/firmware-update/store.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/sikmir/Projects/wb/homeui/test/react/firmware-update/store.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import React from 'react';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1495:14)

 FAIL  test/react/firmware-update/modal.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/sikmir/Projects/wb/homeui/test/react/firmware-update/modal.test.js:5
    import React from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1495:14)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        1.413 s
Ran all test suites matching /test\/react/i
```

2023-06-16 07:04 UTC, lostpoint-ru commented on app/lib/css-spinners
Я, честно говоря, тоже не понял, такое ощущение что какие обновления зависимостей или что-то такое. Я руками там ничего не трогал.

2023-06-16 07:05 UTC, lostpoint-ru commented on test/react/firmware-update/modal.test.js
> +it('constructor without id', () => {
Пройдусь по названиям, поправлю)

2023-06-16 07:05 UTC, lostpoint-ru commented
> Что-то у меня не взлетели тесты:

А ты зависимости ставил? Я вроде все изменения package.json коммитил.

2023-06-16 07:25 UTC, sikmir commented
> > Что-то у меня не взлетели тесты:
> 
> А ты зависимости ставил? Я вроде все изменения package.json коммитил.

Не хватало babel.config.js. Теперь все ок:

2023-06-16 07:25 UTC, sikmir commented
> > Что-то у меня не взлетели тесты:
> 
> 
> А ты зависимости ставил? Я вроде все изменения package.json коммитил.
 
Не хватало babel.config.js. Теперь все ок:

Test Suites: 2 passed, 2 total
Tests:       45 passed, 45 total

2023-06-19 12:34 UTC, KraPete requested changes
Мне не нравится babel.config.js. Фактически настройки babel у нас расползаются, т.к. настройки для сборки основного поекта прописаны в webpack.config.js. Надо использовать идентичные везде.

Ещё у нас в webpack.config.js есть ветка сборки для тестов, она кривая. Нужна ли нам эта ветка? Как вызывается webpack при сборке тестов? Что и как он собирает?

2023-06-21 10:37 UTC, KraPete commented on debian/changelog
> +  * Add some React tests
Стоит написать, что нет изменений для пользователя. Что такое React? Зачем к нему тесты? Зачем пользователю вообще это знать?

2023-06-21 10:47 UTC, KraPete approved these changes

2023-06-21 11:00 UTC, merged