Feature/dm
wirenboard/homeui pull request #518
Opened 2024-03-04 06:07 UTC by KraPete

Device manager interface

2024-03-05 07:18 UTC, ninedev-i requested changes

2024-03-05 07:18 UTC, ninedev-i commented on app/scripts/react-directives/device-manager/pageStore.js
> +  let groups = {};
Почему бы логику со всей этой сортировкой не переложить на плечи бэкенда?

2024-03-05 07:18 UTC, ninedev-i commented on app/scripts/react-directives/device-manager/pageStore.js
> +    return this.confirmModalState.show(
Я бы предложил логику с модальными окнами вынести из стора в компонент. Минорное

2024-03-05 07:40 UTC, KraPete commented on app/scripts/react-directives/device-manager/pageStore.js
> +  let groups = {};
Сортировка зависит от выбранного языка интефейса, мы на бэкенд его не пробрасываем. Но да. Это место я буду менять, делать отдельные запросы для получения списка типа устройств и схем к ним. Сейчас пока всё получется одним большим JSON.

2024-03-05 07:41 UTC, KraPete commented on app/scripts/react-directives/device-manager/pageStore.js
> +    return this.confirmModalState.show(
Можешь пример минимальный накидать, как бы ты сделал?

2024-03-05 07:58 UTC, ninedev-i commented on app/scripts/react-directives/device-manager/pageStore.js
> +    return this.confirmModalState.show(
А, стоп, этот mobx используется на странице с angular. Тогда у меня пока предложений нет

2024-03-05 08:07 UTC, KraPete commented on app/scripts/react-directives/device-manager/pageStore.js
> +    return this.confirmModalState.show(
mobx здесь с реактом используется, но основной каркас на ангуляре.

2024-03-06 07:59 UTC, ninedev-i approved these changes

2024-03-06 08:10 UTC, KraPete commented on app/scripts/json-editor/group-editor.js
> +        this.title.classList.add('disable_collapse');
Сделал в одну строчку

2024-03-07 05:25 UTC, KraPete commented
Rebase https://github.com/wirenboard/homeui/pull/522

2024-03-07 05:25 UTC, closed without merging