Load schemas in wb-mqtt-serial config editor on demand
wirenboard/homeui pull request #525
Opened 2024-03-19 06:26 UTC by KraPete

Схема настроек, список типов устройств и схемы настроек конкретных типов устройств теперь запрашиваются по мере необходимости через отдельный RPC

2024-03-19 07:38 UTC, KraPete commented
testing set
```
echo "deb http://deb.wirenboard.com/all experimental.serial-rpc main" > /etc/apt/sources.list.d/serial-rpc.list
```

2024-03-19 10:55 UTC, ninedev-i requested changes

2024-03-19 13:17 UTC, KraPete commented on app/scripts/react-directives/device-manager/device-manager.js
> +        const r = await SerialProxy.Load({ lang: i18n.language });
Переименовал

2024-03-19 13:17 UTC, KraPete commented on app/scripts/react-directives/device-manager/deviceTab.jsx
> +  if (!tab.hasErrors) {
Исправил

2024-03-19 15:11 UTC, ninedev-i approved these changes

2024-03-21 08:07 UTC, ninedev-i commented on app/scripts/json-editor/optional-editor-with-dropdown.js
> +      this.optInCheckbox = document.createElement('input');
А зачем это здесь? Оно же не применяется к верстке

2024-03-21 08:18 UTC, KraPete commented on app/scripts/json-editor/optional-editor-with-dropdown.js
> +      this.optInCheckbox = document.createElement('input');
json-editor для всех необязательных параметров рисует чекбокс. Я сделал для таких параметров отдельный редактор. В нём нет этого чекбокса и нет свойства `optInCheckbox`. json-editor же иногда явно обращается к нему. Лезть в код json-editor'а не хочу, потому вот такой костыль

2024-03-21 09:27 UTC, ninedev-i commented on app/scripts/json-editor/optional-editor-with-dropdown.js
> +      this.optInCheckbox = document.createElement('input');
Сомнительно, но оукей

2024-03-26 09:29 UTC, closed without merging