Add multiple matched templates warning
wirenboard/homeui pull request #543
Opened 2024-04-23 14:11 UTC by KraPete

Add warning if multiple device templates match the same scanned device in wb-mqtt-serial config

![image](https://github.com/wirenboard/homeui/assets/86825564/727ebdd6-f8cc-4d17-8ad6-aa87646de16a)

2024-04-24 12:41 UTC, ninedev-i requested changes

2024-04-24 12:41 UTC, ninedev-i commented on app/scripts/react-directives/device-manager/scan/scanPageStore.js
>    get title() {
Дублирует метод get name

2024-04-25 03:56 UTC, KraPete commented on app/scripts/react-directives/device-manager/scan/scanPageStore.js
>    get title() {
Убрал

2024-04-25 05:22 UTC, ninedev-i approved these changes

2024-04-25 06:43 UTC, merged