add separate chunks to decrease bundle weight
wirenboard/homeui pull request #547
Opened 2024-04-25 07:06 UTC by ninedev-i

2024-04-26 05:40 UTC, KraPete requested changes
1. Сломались переключатели на странице "Устройства"
![Screenshot_20240426_102212](https://github.com/wirenboard/homeui/assets/86825564/bcded402-c7c2-4884-83ea-9d830cf71c7a)
2. Сломался запрос данных на странице "История". Точнее там всё сломалось, кроме начального состояния
3. Сломалась плашка с уровнем доступа
![Screenshot_20240426_102533](https://github.com/wirenboard/homeui/assets/86825564/d20349c8-b7b8-4db7-836e-7ebfa0cfff39)
4. Сломалась загрузка уже созданных правил, на странице "Правила"
5. Сломалось переключение интерфейса с английского на русский через Settings/Web UI/UI locale
6. Сломалась кнопочка "Скачать архив rootfs" на странице "Настройки/Система"
7. Сломалось скачивание диагностического архива там же

2024-04-26 05:40 UTC, KraPete commented on debian/changelog
> +wb-mqtt-homeui (2.84.6) stable; urgency=medium
Давай увеличим minor, всё таки изменения достаточно масштабные

2024-05-02 12:30 UTC, ninedev-i commented on debian/changelog
> +wb-mqtt-homeui (2.84.6) stable; urgency=medium
done

2024-05-02 12:30 UTC, ninedev-i commented
> 1. Сломались переключатели на странице "Устройства"
>    ![Screenshot_20240426_102212](https://private-user-images.githubusercontent.com/86825564/325857233-bcded402-c7c2-4884-83ea-9d830cf71c7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTMyODMsIm5iZiI6MTcxNDY1Mjk4MywicGF0aCI6Ii84NjgyNTU2NC8zMjU4NTcyMzMtYmNkZWQ0MDItYzdjMi00ODg0LTgzZWEtOWQ4MzBjZjcxYzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEyMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjdlZGM0MWUyZjk1ZTNiZGFjMDgxYmQ2NGFjYmEzOGU4NzU2MTBjMGVkMDJkMjNiYjc0MWZjZTFiYmVlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5q1l4mMoNP_ssdE5FhyYrsJZFKL2WnVyWnnBvDCAKgM)
> 2. Сломался запрос данных на странице "История". Точнее там всё сломалось, кроме начального состояния
> 3. Сломалась плашка с уровнем доступа
>    ![Screenshot_20240426_102533](https://private-user-images.githubusercontent.com/86825564/325857768-d20349c8-b7b8-4db7-836e-7ebfa0cfff39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTMyODMsIm5iZiI6MTcxNDY1Mjk4MywicGF0aCI6Ii84NjgyNTU2NC8zMjU4NTc3NjgtZDIwMzQ5YzgtYjdiOC00ZGI3LTgzNmUtN2ViZmEwY2ZmZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDEyMjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmODQzZmUyY2Q4NjEwYjUyMmRlYzMwOTZiOWI4N2E3YjU1YzUxYmNlZTdmZjE4MzA4ZjE3ZTIzMjQwYjg4YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VdLfdV_Mq8gq3fhqf6zgBcGqyLDM5cV_kSPeYiLtzDc)
> 4. Сломалась загрузка уже созданных правил, на странице "Правила"
> 5. Сломалось переключение интерфейса с английского на русский через Settings/Web UI/UI locale
> 6. Сломалась кнопочка "Скачать архив rootfs" на странице "Настройки/Система"
> 7. Сломалось скачивание диагностического архива там же

все исправил

2024-05-03 06:47 UTC, KraPete commented
@ninedev-i 
1. Всё ещё сломано редактирование уже созданных правил
2. Не переключается язык интерфейса с русского на английский через Settings/Web UI/UI locale
3. На странице Настройки/Система в консоль падает ошибка, которой не было на testing'е
4. Сборка в дженкинсе не проходит

2024-05-03 09:51 UTC, KraPete approved these changes

2024-05-06 06:16 UTC, merged