Feature/70182 update from cloud
wirenboard/homeui pull request #549
Opened 2024-05-02 08:08 UTC by vdromanov

Запрет прошивки контроллера из облака fit-ом без предустановленного wb-cloud-agent

связанных PR-ов - куча => проще всего потыкать:
обновиться из тестинг-сета http://deb.wirenboard.com/all@experimental.update-from-cloud:main

ребут
подключить к облаку
обновиться из облака stable-ом; увидеть ругательства
обновиться fit-ом [с поддержкой обновления из облака](https://jenkins.wirenboard.com/job/pipelines/job/build-image/6241/); не увидеть ругательства

![image](https://github.com/wirenboard/homeui/assets/25829054/4e1f743c-d5e0-40c7-a5b4-9852a29d53c0)
![image](https://github.com/wirenboard/homeui/assets/25829054/52581fc5-a12a-4707-9d10-47ab80481ab3)

2024-05-02 08:14 UTC, vdromanov commented on app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
> +    if (window.location.href.indexOf('wirenboard.cloud') !== -1) {
гугол сказал, что такое будет работать даже в ie

2024-05-03 09:05 UTC, webconn requested changes

2024-05-03 09:05 UTC, webconn commented on app/scripts/react-directives/firmware-update/firmwareUpdateWidget.jsx
> +    if (window.location.href.indexOf('wirenboard.cloud') !== -1) {
нене, это плохое, с on-premises домен будет другой

2024-06-11 09:44 UTC, vdromanov commented
изменения @webconn я тыкал - всё работает!

2024-06-13 09:52 UTC, webconn approved these changes

2024-06-21 13:30 UTC, merged