Show disconnected devices in wb-mqtt-serial-config
wirenboard/homeui pull request #554
Opened 2024-05-23 12:59 UTC by KraPete

* Add duplicate MQTT id checking in wb-mqtt-serial config
  * Show disconnected devices in wb-mqtt-serial config

Ветка давно не синхронизировалась с мастером и feature/collision-detection не влита. Так что pr не в мастер

2024-05-27 09:20 UTC, ninedev-i requested changes

2024-05-27 09:20 UTC, ninedev-i commented on app/scripts/react-directives/device-manager/config-editor/deviceTab.jsx
> +  let showSign = false;
здесь нужно использовать useState, вместо простой переменной, ибо при перерендеринге что-то может пойти не так.

2024-05-27 10:18 UTC, ninedev-i approved these changes
lgtm!

2024-05-28 04:57 UTC, KraPete commented
Rebase https://github.com/wirenboard/homeui/pull/555

2024-05-28 04:57 UTC, closed without merging

2024-05-28 04:57 UTC, KraPete commented on app/scripts/react-directives/device-manager/config-editor/deviceTab.jsx
> +  let showSign = false;
Поменял в веточке с ребейзом, как в телеге договорились