Feature/setup device
wirenboard/homeui pull request #559
Opened 2024-06-04 11:20 UTC by KraPete

При добавлении устройства в конфиг wb-mqtt-serial из сканирования теперь можно изменить настроки связи этого устройства

2024-06-05 08:07 UTC, ninedev-i requested changes

2024-06-05 08:07 UTC, ninedev-i commented on app/scripts/react-directives/device-manager/config-editor/configEditorPageStore.js
> +    let commonCfg = {
Если в device.cfg нет больше ничего, то достаточно ```let commonCfg = {...device.cfg}```

2024-06-05 08:07 UTC, ninedev-i commented on app/scripts/react-directives/device-manager/scan/setupDevicesModalState.js
> +    this.showSetupPort = showSetupPort;
Это странно - может тут значение должно быть true? И вообще, надо ли нам два параметра   showSetupPort и setupPort?
Если нужно, может пусть это будет геттер? ```get showSetupPort() { return !!this.setupPort }```

2024-06-06 04:11 UTC, KraPete commented on app/scripts/react-directives/device-manager/config-editor/configEditorPageStore.js
> +    let commonCfg = {
Есть ещё `data_bits`, который тут не используется

2024-06-06 04:12 UTC, KraPete commented on app/scripts/react-directives/device-manager/scan/setupDevicesModalState.js
> +    this.showSetupPort = showSetupPort;
Переделал

2024-06-06 08:13 UTC, ninedev-i approved these changes

2024-06-20 06:02 UTC, closed without merging