* Add open ports probe results widget
wirenboard/homeui pull request #577
Opened 2024-06-29 17:44 UTC by lostpoint-ru

Бэкпорт https://github.com/wirenboard/homeui/pull/576

В ченджлоге пишарм зачем-то решил поделить на ноль пробелы в конце строки.

2024-06-30 18:46 UTC, evgeny-boger requested changes

2024-06-30 18:46 UTC, evgeny-boger commented on app/scripts/app.js
> +  .directive('fullscreenToggle', fullscreenToggleDirective)
лишнее вроде попало

2024-06-30 19:24 UTC, lostpoint-ru commented on app/scripts/app.js
> +  .directive('fullscreenToggle', fullscreenToggleDirective)
Упс, проглядел.

Поправил.

2024-07-01 08:49 UTC, ninedev-i approved these changes
lgtm

2024-07-01 14:54 UTC, evgeny-boger approved these changes

2024-07-01 16:04 UTC, merged