Add new available firmware notification
wirenboard/homeui pull request #597
Opened 2024-07-24 06:15 UTC by KraPete

![Screenshot_20240724_111436](https://github.com/user-attachments/assets/d8f41466-a042-41b6-b3dd-8fcf2713166f)

2024-07-24 11:13 UTC, lostpoint-ru requested changes

2024-07-24 11:13 UTC, lostpoint-ru commented on app/scripts/i18n/react/locales/en/translations.json
> +         "new-firmware": "Firmware {{firmware}}, there is a newer version {{newFirmware}}"
```suggestion
         "new-firmware": "Current firmware version is {{firmware}}, update to version {{newFirmware}} is available"
```

2024-07-24 11:13 UTC, lostpoint-ru commented on app/scripts/i18n/react/locales/ru/translations.json
> +         "new-firmware": "Прошивка {{firmware}}, есть новая {{newFirmware}}"
```suggestion
         "new-firmware": "Текущая версия прошивки {{firmware}}, доступно обновление до версии {{newFirmware}}"
```

2024-09-12 12:57 UTC, KraPete commented
Всё влито тут https://github.com/wirenboard/homeui/pull/607

2024-09-12 12:57 UTC, closed without merging