SOFT-3992
wirenboard/homeui pull request #603
Opened 2024-08-14 13:29 UTC by ninedev-i

fix devices page toggled accordions

2024-08-16 09:50 UTC, webconn approved these changes

2024-08-16 09:50 UTC, webconn commented on debian/changelog
> +  * Fix devices toggled on page refresh
```suggestion
  * Fix devices panes collapsed in one column after page refresh
```

чтобы из кумулятивного ченджлога потом без контекста проще было понять, что произошло

2024-08-16 09:50 UTC, webconn commented
ну и да, на контроллере проверил, работает

2024-08-19 05:06 UTC, KraPete requested changes
Сломалось восстановление свёрнутых элементов. Сворачиваю какие-то устройства, жму F5, они снова развёрнуты, а свёрнуты совсем другие.
Возможно, это никогда и не работало, но тогда уж пусть все будут развёрнутые после перезагрузки страницы

2024-08-20 05:02 UTC, ninedev-i commented on debian/changelog
> +  * Fix devices toggled on page refresh
fixed

2024-08-20 07:38 UTC, KraPete requested changes

2024-08-20 07:38 UTC, KraPete commented on app/scripts/controllers/devicesController.js
> +        const aCompare = a._nameTranslations[this.locale] || a.name;
Там есть метод `getName(lang)`

2024-08-20 07:47 UTC, ninedev-i commented on app/scripts/controllers/devicesController.js
> +        const aCompare = a._nameTranslations[this.locale] || a.name;
Спасибо, заиспользовал

2024-08-20 07:48 UTC, KraPete approved these changes

2024-08-20 08:00 UTC, merged