Custom/keaz
wirenboard/homeui pull request #612
Opened 2024-08-29 11:05 UTC by ninedev-i

Собственная тема для КЭАЗ
![image](https://github.com/user-attachments/assets/cfdc2a41-0845-48b6-b1ec-8d63797bb268)
![image](https://github.com/user-attachments/assets/b1c070fc-ef91-4cf2-b539-b6c27b7f6950)

2024-09-03 11:15 UTC, webconn commented on app/styles/css/bootstrap.min.css
а тут что поменялось? это ж библиотека, версия в заголовке та же

2024-09-13 05:03 UTC, KraPete requested changes
Хочется максимум измененийв тему вынести, пусть это не один файл будет

2024-09-13 05:03 UTC, KraPete commented on app/index.ejs
> +    <title>KEAZ OptiSmart WEB</title>
Можно это тоже как-то в тему вынести или в отдельный файл?

2024-09-13 05:03 UTC, KraPete commented on app/index.ejs
> +                <img src="images/logo.png" alt="KEAZ OptiSmart WEB">
И лого тоже бы в тему

2024-09-13 05:03 UTC, KraPete commented on app/styles/css/bootstrap.min.css
Присоединяюсь к вопросу

2024-09-13 05:03 UTC, KraPete commented on app/styles/css/new.css
> +.navbar-brand img {
Это бы в тему вынести

2024-09-13 06:07 UTC, ninedev-i commented on app/styles/css/bootstrap.min.css
Я цвета выносил в переменную

2024-10-15 08:43 UTC, KraPete approved these changes

2024-10-15 08:49 UTC, merged