add realtime value show to range slider
wirenboard/homeui pull request #613
Opened 2024-08-29 14:07 UTC by ninedev-i

Для range slider добавил отображение значение в реальном времени. При этом запрос на изменение будет отправлен когда мышка будет отпущена.
![image](https://github.com/user-attachments/assets/d87bd6c0-3201-409f-8005-ebdc72df105c)

2024-08-29 14:47 UTC, KraPete commented on app/styles/main.css
> +  min-height: 18px;
А это зачем?

2024-08-29 14:47 UTC, KraPete commented on app/styles/main.css
> +.display-cell .ngrs-value-min .ng-binding {
И это?

2024-08-29 16:17 UTC, ninedev-i commented on app/styles/main.css
> +  min-height: 18px;
Сам слайдер добавляет значение под ним, для этого надо увеличить высоту самого слайдера.

2024-08-29 16:18 UTC, ninedev-i commented on app/styles/main.css
> +.display-cell .ngrs-value-min .ng-binding {
А здесь он зачем то отображает минимальное значение — 0. Решил что это лишнее

2024-08-30 04:01 UTC, KraPete approved these changes

2024-08-30 05:37 UTC, webconn approved these changes
мне нравится, выглядит стильно

2024-08-30 05:54 UTC, KraPete requested changes
![Screenshot_20240830_105421](https://github.com/user-attachments/assets/5f310dd7-4e04-4f79-b51a-4089346c6c40)

Если задать единицы измерения, будет странно

2024-08-30 05:56 UTC, KraPete commented
```
defineVirtualDevice('my-virtual-device', {
    cells: {
      ControlName2: {
        title: "Name 2",
        type: "range",
        units: "Hz",
        value: 25,
        max: 100,
        min: 1
      }
    }
});

getDevice("my-virtual-device").getControl("ControlName2").setUnits("Hz");
```

Вот правило для тестирования

2024-08-30 05:59 UTC, KraPete commented
Раньше было так
![Screenshot_20240830_105857](https://github.com/user-attachments/assets/83c45435-1a69-4f5d-8cac-8ad08b5f92d3)

2024-08-30 08:50 UTC, ninedev-i commented
![image](https://github.com/user-attachments/assets/099ae5b2-2f7a-4152-a205-5511282174ed)

2024-08-30 09:46 UTC, KraPete approved these changes

2024-09-02 07:52 UTC, merged