fix MQTT topics search
wirenboard/homeui pull request #631
Opened 2024-10-03 12:30 UTC by ninedev-i

Исправил поиск в MQTT топиках
https://wirenboard.youtrack.cloud/issue/SOFT-3048

2024-10-04 05:01 UTC, KraPete requested changes
Я не понял из задачи, что было не так

2024-10-04 07:45 UTC, sikmir commented
> Я не понял из задачи, что было не так

Например вот:
<img width="1052" alt="image(1)" src="https://github.com/user-attachments/assets/4655b891-a48d-477b-b64b-43def796588c">

2024-10-07 04:58 UTC, KraPete commented
Ну так ничего не изменилось 
![Screenshot_20241007_095747](https://github.com/user-attachments/assets/04896c5e-f7fe-47bd-8615-a371f0d02269)

2024-10-07 04:59 UTC, KraPete requested changes
Всё ещё не понимаю, какую задачу решали. Если то, что написал Николай, то ничего не изменилось

2024-10-07 06:31 UTC, sikmir commented
> Ну так ничего не изменилось ![Screenshot_20241007_095747](https://private-user-images.githubusercontent.com/86825564/374036310-04896c5e-f7fe-47bd-8615-a371f0d02269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODI5MzMsIm5iZiI6MTcyODI4MjYzMywicGF0aCI6Ii84NjgyNTU2NC8zNzQwMzYzMTAtMDQ4OTZjNWUtZjdmZS00N2JkLTg2MTUtYTM3MWYwZDAyMjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA2MzAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZjVhNDFmM2MyZjE3NWFmOTE5Yjg3YTI4ZThkOWQ1NDQzYmU4ZmNhYWVmODdjNjEyZWYwZDFlYTRkNTZiMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IUlDPIifnG8A7ABxs0b33z5XiqLIFeOZY5QWMIbIvrw)

тут же в значении есть 99

2024-10-07 07:02 UTC, ninedev-i commented
@KraPete раньше неправильно работал поиск по числам, потому что искал вообще по всем полям которые приходят с бека, но не рисуются в таблице, а теперь находит то что должен находить, а то что не должен находить не находит

2024-10-07 07:15 UTC, KraPete approved these changes

2024-10-07 07:51 UTC, merged