Add bootloader update
wirenboard/homeui pull request #636
Opened 2024-10-11 07:44 UTC by KraPete

Добавил возможность обновить бутлоадер у наших устройств

![Screenshot_20241011_124436](https://github.com/user-attachments/assets/f0634fbe-3ec6-4fcd-873e-988573ec9030)

2024-10-11 14:23 UTC, ninedev-i requested changes

2024-10-11 14:23 UTC, ninedev-i commented on app/scripts/i18n/react/locales/ru/translations.json
> +         "new-bootloader": "Загрузчик {{current}}, есть новый {{available}}",
Не по человечески как-то, может лучше:
Доступна новая версия Загрузчика — {{available}}. Текущая версия: {{current}}.

2024-10-11 14:23 UTC, ninedev-i commented on debian/changelog
> +  *
Тут пусто

2024-10-15 06:41 UTC, KraPete commented on app/scripts/i18n/react/locales/ru/translations.json
> +         "new-bootloader": "Загрузчик {{current}}, есть новый {{available}}",
Поправил

2024-10-15 06:41 UTC, KraPete commented on debian/changelog
> +  *
Поправил

2024-10-15 07:12 UTC, ninedev-i requested changes

2024-10-15 07:12 UTC, ninedev-i commented on app/scripts/i18n/react/locales/ru/translations.json
> +         "new-firmware": "Доступна новая версия прошивки: {{available}}. Текущая: {{current}}",
Может все же текущАЯ версия?

2024-10-15 07:34 UTC, ninedev-i requested changes

2024-10-15 07:34 UTC, ninedev-i commented on app/scripts/i18n/react/locales/ru/translations.json
> +         "new-firmware": "Доступна новая версия прошивки: {{available}}. Текущая: {{current}}",
а в cant-update-new-bootloader?

2024-10-15 07:59 UTC, KraPete commented on app/scripts/i18n/react/locales/ru/translations.json
> +         "new-firmware": "Доступна новая версия прошивки: {{available}}. Текущая: {{current}}",
Там поменял

2024-10-15 08:08 UTC, ninedev-i approved these changes

2024-10-17 09:49 UTC, merged